web: daphne -b 0.0.0.0 -p $PORT hostelconnect.asgi:application
release: python manage.py migrate
worker: celery -A hostelconnect worker --loglevel=info
beat: celery -A hostelconnect beat --loglevel=info
