# Generated by Django 4.2.10 on 2026-04-12 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostelconnect_audit', '0002_remove_auditlog_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='after_state',
            field=models.JSONField(blank=True, help_text='Optional snapshot of resource after mutation (immutable audit extension).', null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='before_state',
            field=models.JSONField(blank=True, help_text='Optional snapshot of resource before mutation (immutable audit extension).', null=True),
        ),
    ]
