# Generated by Django 4.2.10 on 2026-02-03 12:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inapp_messages", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="message",
            new_name="messages_me_recipie_145bf3_idx",
            old_name="messages_me_recipient_4f6d40_idx",
        ),
        migrations.RenameIndex(
            model_name="message",
            new_name="messages_me_sender__8edce9_idx",
            old_name="messages_me_sender_2d5385_idx",
        ),
    ]
