# Generated by Django 4.2.27 on 2026-02-09 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['status'], name='attendance__status_132c06_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['attendance_date', 'status'], name='attendance__attenda_f3ac94_idx'),
        ),
    ]
