# Generated by Django 4.2.10 on 2026-03-01 01:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0012_building_attendance_taker_role_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendance', '0003_attendance_attendance__status_132c06_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rooms.building'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='floor',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendance',
            name='locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_locked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('on_leave', 'On Leave'), ('out_gatepass', 'Out (Gatepass)'), ('late', 'Late'), ('excused', 'Excused'), ('sick', 'Sick Leave')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['block', 'attendance_date'], name='attendance__block_i_0c78ac_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['block', 'floor', 'attendance_date'], name='attendance__block_i_8c66dc_idx'),
        ),
    ]
