# Generated by Django 4.2.10 on 2026-03-01 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_attendance_block_attendance_floor_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='attendance',
            new_name='att_user_date_idx',
            old_name='attendance__user_id_1e2bf1_idx',
        ),
        migrations.RenameIndex(
            model_name='attendance',
            new_name='att_status_idx',
            old_name='attendance__status_132c06_idx',
        ),
        migrations.RenameIndex(
            model_name='attendance',
            new_name='att_date_status_idx',
            old_name='attendance__attenda_f3ac94_idx',
        ),
        migrations.RenameIndex(
            model_name='attendance',
            new_name='att_block_date_idx',
            old_name='attendance__block_i_0c78ac_idx',
        ),
        migrations.RenameIndex(
            model_name='attendance',
            new_name='att_block_floor_date_idx',
            old_name='attendance__block_i_8c66dc_idx',
        ),
    ]
