# Generated by Django 4.2.10 on 2026-03-08 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_alter_attendance_created_at_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='attendancereport',
            index=models.Index(fields=['user', 'period'], name='attendance__user_id_6b1302_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancereport',
            index=models.Index(fields=['start_date', 'end_date'], name='attendance__start_d_34e11b_idx'),
        ),
    ]
