# Generated by Django 4.2.10 on 2026-03-20 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_backfill_attendance_college'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='attendance',
            name='att_college_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='attendance',
            name='att_college_status_idx',
        ),
    ]
