# Generated by Django 4.2.10 on 2026-04-04 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0012_attendance_trace_id_attendancereport_trace_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='attendancereport',
            name='deleted_at',
        ),
    ]
