# Generated by Django 4.2.10 on 2026-04-06 03:36

from django.db import migrations, models
import django.db.models.deletion


def backfill_attendance_reports(apps, schema_editor):
    AttendanceReport = apps.get_model('attendance', 'AttendanceReport')

    seen_keys = set()
    reports = AttendanceReport.objects.all().order_by(
        'user_id',
        'period',
        'start_date',
        'end_date',
        '-updated_at',
        '-created_at',
    )

    for report in reports.iterator():
        dedupe_key = (report.user_id, report.period, report.start_date, report.end_date)
        if dedupe_key in seen_keys:
            report.delete()
            continue

        seen_keys.add(dedupe_key)

        if getattr(report, 'college_id', None):
            report.tenant_id = str(report.college_id)
            report.save(update_fields=['tenant_id'])
            continue

        user = report.user
        if getattr(user, 'college_id', None):
            report.college_id = user.college_id
            report.tenant_id = str(user.college_id)
            report.save(update_fields=['college', 'tenant_id'])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0011_remove_college_deleted_at_and_more'),
        ('attendance', '0013_remove_attendance_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancereport',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_reports', to='colleges.college'),
        ),
        migrations.RunPython(backfill_attendance_reports, noop_reverse),
        migrations.AddConstraint(
            model_name='attendancereport',
            constraint=models.UniqueConstraint(fields=('user', 'period', 'start_date', 'end_date'), name='attendance_report_unique_period_window'),
        ),
        migrations.AddConstraint(
            model_name='attendancereport',
            constraint=models.CheckConstraint(check=models.Q(('end_date__gte', models.F('start_date'))), name='attendance_report_end_date_gte_start_date'),
        ),
        migrations.AddConstraint(
            model_name='attendancereport',
            constraint=models.CheckConstraint(check=models.Q(('total_days__gte', 0)), name='attendance_report_total_days_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='attendancereport',
            constraint=models.CheckConstraint(check=models.Q(('present_days__gte', 0)), name='attendance_report_present_days_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='attendancereport',
            constraint=models.CheckConstraint(check=models.Q(('absent_days__gte', 0)), name='attendance_report_absent_days_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='attendancereport',
            constraint=models.CheckConstraint(check=models.Q(('late_days__gte', 0)), name='attendance_report_late_days_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='attendancereport',
            constraint=models.CheckConstraint(check=models.Q(('excused_days__gte', 0)), name='attendance_report_excused_days_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='attendancereport',
            constraint=models.CheckConstraint(check=models.Q(('percentage__gte', 0.0), ('percentage__lte', 100.0)), name='attendance_report_percentage_between_0_100'),
        ),
    ]
