# Generated by Django 4.2.10 on 2026-02-03 13:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hostelconnect_auth", "0002_alter_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("student", "Student"),
                    ("staff", "Staff"),
                    ("admin", "Admin"),
                    ("super_admin", "Super Admin"),
                    ("head_warden", "Head Warden"),
                    ("warden", "Warden"),
                    ("chef", "Chef"),
                    ("gate_security", "Gate Security"),
                    ("security_head", "Security Head"),
                ],
                default="student",
                max_length=20,
            ),
        ),
    ]
