# Generated by Django 4.2.10 on 2026-03-01 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0012_building_attendance_taker_role_and_more'),
        ('hostelconnect_auth', '0006_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assigned_blocks',
            field=models.ManyToManyField(blank=True, related_name='assigned_staff', to='rooms.building'),
        ),
        migrations.AddField(
            model_name='user',
            name='assigned_floors',
            field=models.JSONField(blank=True, default=list, help_text='List of floor numbers assigned to this HR/Warden'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_student_hr',
            field=models.BooleanField(default=False, help_text='Designates if this student has HR authority'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('staff', 'Staff'), ('admin', 'Admin'), ('super_admin', 'Super Admin'), ('head_warden', 'Head Warden'), ('warden', 'Warden'), ('chef', 'Chef'), ('head_chef', 'Head Chef'), ('gate_security', 'Gate Security'), ('security_head', 'Security Head'), ('hr', 'HR Rep')], default='student', max_length=20),
        ),
    ]
