# Generated by Django 4.2.10 on 2026-03-12 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostelconnect_auth', '0012_user_hostelconne_role_242f53_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='student_type',
            field=models.CharField(choices=[('hosteller', 'Hosteller'), ('day_scholar', 'Day Scholar')], default='hosteller', help_text='Indicates if the student resides in hostel or is a day scholar.', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('staff', 'Staff'), ('admin', 'Admin'), ('super_admin', 'Super Admin'), ('head_warden', 'Head Warden'), ('warden', 'Warden'), ('chef', 'Chef'), ('head_chef', 'Head Chef'), ('gate_security', 'Gate Security'), ('security_head', 'Security Head'), ('hr', 'HR Rep'), ('pd', 'Physical Director'), ('pt', 'Physical Trainer')], default='student', max_length=20),
        ),
    ]
