# Generated by Django 4.2.10 on 2026-03-31 11:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hostelconnect_auth", "0015_user_semester_user_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="late_count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Cumulative number of times the student returned late.",
            ),
        ),
    ]
