# Generated by Django 4.2.27 on 2026-02-09 03:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('visitor_name', models.CharField(max_length=100)),
                ('relationship', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=15)),
                ('purpose', models.TextField()),
                ('check_in', models.DateTimeField(auto_now_add=True)),
                ('check_out', models.DateTimeField(blank=True, null=True)),
                ('id_proof_number', models.CharField(help_text='Last 4 digits of ID proof', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-check_in'],
                'indexes': [models.Index(fields=['student'], name='visitors_vi_student_8e1d33_idx'), models.Index(fields=['visitor_name'], name='visitors_vi_visitor_9ff14d_idx'), models.Index(fields=['check_in'], name='visitors_vi_check_i_eb52bf_idx')],
            },
        ),
    ]
