# Generated by Django 4.2.10 on 2026-02-16 18:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('visitors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorPreRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('visitor_name', models.CharField(max_length=100)),
                ('relationship', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=15)),
                ('purpose', models.TextField()),
                ('expected_date', models.DateField(help_text='Expected date of visit')),
                ('expected_time', models.TimeField(blank=True, help_text='Expected arrival time', null=True)),
                ('id_proof_number', models.CharField(blank=True, help_text='Last 4 digits of ID proof', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('checked_in', 'Checked In'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-expected_date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='visitorlog',
            name='photo_url',
            field=models.URLField(blank=True, help_text='Photo URL of the visitor'),
        ),
        migrations.AddIndex(
            model_name='visitorlog',
            index=models.Index(fields=['is_active'], name='visitors_vi_is_acti_77b01d_idx'),
        ),
        migrations.AddField(
            model_name='visitorpreregistration',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitor_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='visitorpreregistration',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitor_pre_registrations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='visitorlog',
            name='pre_registration',
            field=models.ForeignKey(blank=True, help_text='Linked pre-registration if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitor_logs', to='visitors.visitorpreregistration'),
        ),
        migrations.AddIndex(
            model_name='visitorpreregistration',
            index=models.Index(fields=['student', 'status'], name='visitors_vi_student_f8311d_idx'),
        ),
        migrations.AddIndex(
            model_name='visitorpreregistration',
            index=models.Index(fields=['expected_date', 'status'], name='visitors_vi_expecte_440d45_idx'),
        ),
    ]
