# Generated by Django 4.2.10 on 2026-03-05 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0003_alter_visitorlog_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='visitorlog',
            name='visitors_vi_student_8e1d33_idx',
        ),
        migrations.RemoveIndex(
            model_name='visitorlog',
            name='visitors_vi_check_i_eb52bf_idx',
        ),
        migrations.RemoveIndex(
            model_name='visitorlog',
            name='visitors_vi_is_acti_77b01d_idx',
        ),
        migrations.AddIndex(
            model_name='visitorlog',
            index=models.Index(fields=['student', '-check_in'], name='visitor_student_checkin_idx'),
        ),
        migrations.AddIndex(
            model_name='visitorlog',
            index=models.Index(fields=['is_active', '-check_in'], name='visitor_active_checkin_idx'),
        ),
        migrations.AddIndex(
            model_name='visitorlog',
            index=models.Index(fields=['student', 'is_active'], name='visitor_student_active_idx'),
        ),
    ]
