# Generated by Django 4.2.10 on 2026-03-20 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0006_backfill_visitor_college'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='visitorlog',
            name='visitor_college_checkin_idx',
        ),
    ]
