# Generated by Django 4.2.10 on 2026-04-04 06:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0003_healthcheck_is_deleted_healthcheck_tenant_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthcheck',
            name='deleted_at',
        ),
        migrations.AddField(
            model_name='healthcheck',
            name='trace_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Global Trace ID for request correlation.'),
        ),
    ]
