# Generated by Django 4.2.27 on 2026-02-09 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='target_audience',
            field=models.CharField(choices=[('all', 'All'), ('students', 'Students'), ('staff', 'Staff'), ('wardens', 'Wardens'), ('chefs', 'Chefs')], default='all', max_length=50),
        ),
    ]
