# Generated by Django 4.2.10 on 2026-02-12 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0009_remove_roomallocation_idx_active_allocations'),
        ('notices', '0002_alter_notice_target_audience'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='target_building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='building_notices', to='rooms.building'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='target_audience',
            field=models.CharField(choices=[('all', 'All'), ('students', 'Students'), ('staff', 'Staff'), ('wardens', 'Wardens'), ('chefs', 'Chefs'), ('block', 'Block-Specific')], default='all', max_length=50),
        ),
        migrations.AddIndex(
            model_name='notice',
            index=models.Index(fields=['target_audience', 'is_published'], name='notices_not_target__748fc9_idx'),
        ),
    ]
