# Generated by Django 4.2.10 on 2026-02-24 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0004_notice_external_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='notices/'),
        ),
    ]
