# Generated by Django 4.2.10 on 2026-03-12 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0007_noticelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='target_audience',
            field=models.CharField(choices=[('all', 'Everyone'), ('students', 'Students'), ('wardens', 'Wardens'), ('chefs', 'Chefs'), ('staff', 'All Staff (Wardens, Chefs, etc.)'), ('admins', 'Administrative Team'), ('block', 'Block-Specific')], default='all', max_length=50),
        ),
    ]
