# Generated by Django 4.2.10 on 2026-03-12 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0008_alter_notice_target_audience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='target_audience',
            field=models.CharField(choices=[('hostellers', 'Hostellers'), ('day_scholars', 'Day Scholars'), ('all_students', 'All Students'), ('all', 'Everyone'), ('students', 'Students'), ('wardens', 'Wardens'), ('chefs', 'Chefs'), ('staff', 'All Staff'), ('admins', 'Administrative Team'), ('block', 'Block-Specific')], default='all', max_length=50),
        ),
    ]
