# Generated by Django 4.2.10 on 2026-04-04 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0012_notice_trace_id_noticelog_college_noticelog_trace_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='noticelog',
            name='deleted_at',
        ),
    ]
