# Generated by Django 4.2.10 on 2026-03-20 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_builder', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='resumeprofile',
            new_name='resume_buil_user_id_5b6e3d_idx',
            old_name='resume_profile_user_idx',
        ),
        migrations.RenameIndex(
            model_name='resumeprofile',
            new_name='resume_buil_college_4be61a_idx',
            old_name='resume_profile_college_idx',
        ),
        migrations.AddField(
            model_name='resumeprofile',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='resumeprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
