# Generated by Django 4.2.27 on 2026-02-09 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_exam',
            field=models.BooleanField(default=False, help_text='Is this an exam period?'),
        ),
        migrations.AddField(
            model_name='event',
            name='is_holiday',
            field=models.BooleanField(default=False, help_text='Is this a college holiday?'),
        ),
    ]
