# Generated by Django 4.2.10 on 2026-02-23 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_eventregistration_status_index'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='eventregistration',
            name='events_reg_status_idx',
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='status',
            field=models.CharField(choices=[('registered', 'Registered'), ('attended', 'Attended'), ('absent', 'Absent'), ('cancelled', 'Cancelled')], db_index=True, default='registered', max_length=20),
        ),
    ]
