# Generated by Django 4.2.10 on 2026-04-03 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_is_holiday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='eventregistration',
            name='deleted_at',
        ),
    ]
