# Generated by Django 4.2.10 on 2026-02-24 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_remove_eventregistration_events_reg_status_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='external_link',
            field=models.URLField(blank=True, help_text='External link (e.g. Google Form)', max_length=500, null=True),
        ),
    ]
