# Generated by Django 4.2.10 on 2026-03-12 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_alter_event_created_at_alter_event_deleted_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SportsBookingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('max_bookings_per_day', models.IntegerField(default=1)),
                ('max_bookings_per_week', models.IntegerField(default=3)),
            ],
            options={
                'verbose_name': 'Sports Booking Configuration',
                'verbose_name_plural': 'Sports Booking Configuration',
            },
        ),
        migrations.CreateModel(
            name='SportsCourt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('name', models.CharField(max_length=100)),
                ('sport_name', models.CharField(help_text='e.g. Badminton, Basketball', max_length=100)),
                ('location_details', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='event',
            name='is_match_ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='min_players',
            field=models.IntegerField(default=1, verbose_name='Min Players'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='check_in_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='match_group_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='qr_code_reference',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='max_participants',
            field=models.IntegerField(blank=True, null=True, verbose_name='Max Players'),
        ),
        migrations.AddField(
            model_name='event',
            name='court',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slots', to='events.sportscourt'),
        ),
    ]
