# Generated by Django 4.2.10 on 2026-03-12 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_sportsbookingconfig_sportscourt_event_is_match_ready_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='target_audience',
            field=models.CharField(choices=[('hostellers', 'Hostellers'), ('day_scholars', 'Day Scholars'), ('all_students', 'All Students'), ('all', 'Everyone')], default='all_students', max_length=50),
        ),
    ]
