# Generated by Django 4.2.10 on 2026-03-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_event_target_audience'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='allow_registration',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='event',
            name='enable_attendance',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='event',
            name='enable_certificates',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='enable_points',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='enable_reminders',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='event',
            name='enable_waitlist',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='event',
            name='event_video',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='gallery_images',
            field=models.JSONField(blank=True, default=list, help_text='Optional list of gallery image URLs'),
        ),
        migrations.AddField(
            model_name='event',
            name='highlight_as_banner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='sponsor_logos',
            field=models.JSONField(blank=True, default=list, help_text='Optional list of sponsor logo URLs'),
        ),
        migrations.AddField(
            model_name='event',
            name='target_department',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='target_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='target_audience',
            field=models.CharField(
                choices=[
                    ('hostellers', 'Hostellers'),
                    ('day_scholars', 'Day Scholars'),
                    ('all_students', 'All Students'),
                    ('staff_only', 'Staff Only'),
                    ('specific_department', 'Specific Department'),
                    ('specific_year', 'Specific Year'),
                    ('all', 'Everyone'),
                ],
                default='all_students',
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='status',
            field=models.CharField(
                choices=[
                    ('registered', 'Registered'),
                    ('waitlisted', 'Waitlisted'),
                    ('attended', 'Attended'),
                    ('absent', 'Absent'),
                    ('cancelled', 'Cancelled'),
                ],
                db_index=True,
                default='registered',
                max_length=20,
            ),
        ),
    ]
