# Generated by Django 4.2.10 on 2026-03-14 02:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0012_points_feedback_tickets"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventregistration",
            name="scan_method",
            field=models.CharField(
                blank=True,
                choices=[("qr", "QR Code"), ("manual", "Manual Entry")],
                max_length=10,
                null=True,
            ),
        ),
    ]
