# Generated by Django 4.2.10 on 2026-03-20 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_eventticket_college'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SportsBookingConfig',
        ),
        migrations.DeleteModel(
            name='SportsCourt',
        ),
        migrations.RemoveIndex(
            model_name='event',
            name='event_college_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='eventregistration',
            name='ereg_college_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='eventregistration',
            name='evtreg_event_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='eventregistration',
            name='evtreg_student_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='eventregistration',
            name='evtreg_college_status_idx',
        ),
    ]
