# Generated by Django 4.2.10 on 2026-03-12 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0004_alter_notification_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='target_audience',
            field=models.CharField(choices=[('hostellers', 'Hostellers'), ('day_scholars', 'Day Scholars'), ('all_students', 'All Students'), ('all', 'Everyone')], default='all_students', max_length=50),
        ),
        migrations.AlterField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['target_audience', '-created_at'], name='notificatio_target__58a2d9_idx'),
        ),
    ]
