# Generated by Django 4.2.10 on 2026-03-20 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_backfill_notification_college'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='notification',
            name='notif_college_created_idx',
        ),
    ]
