# Generated by Django 4.2.10 on 2026-04-01 02:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0010_college_trace_id_collegepolicy_trace_id_and_more'),
        ('notifications', '0009_notification_is_deleted_notification_tenant_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='trace_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Global Trace ID for request correlation.'),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='colleges.college'),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='trace_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Global Trace ID for request correlation.'),
        ),
        migrations.AddField(
            model_name='webpushsubscription',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='colleges.college'),
        ),
        migrations.AddField(
            model_name='webpushsubscription',
            name='trace_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Global Trace ID for request correlation.'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='colleges.college'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['tenant_id', 'is_read'], name='notif_tenant_read_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['tenant_id', '-created_at'], name='notif_tenant_created_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationpreference',
            index=models.Index(fields=['tenant_id', 'user'], name='notifpref_tenant_user_idx'),
        ),
    ]
