# Generated by Django 4.2.10 on 2026-04-04 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0010_notification_trace_id_notificationpreference_college_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='notificationpreference',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='webpushsubscription',
            name='deleted_at',
        ),
    ]
