# Generated by Django 4.2.10 on 2026-03-04 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplinary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplinaryaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='disciplinaryaction',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True),
        ),
    ]
