# Generated by Django 4.2.10 on 2026-03-20 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disciplinary', '0005_disciplinaryaction_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='disciplinaryaction',
            name='disc_college_created_idx',
        ),
        migrations.RenameIndex(
            model_name='disciplinaryaction',
            new_name='disciplinar_severit_6f73ba_idx',
            old_name='disc_severity_idx',
        ),
    ]
