# Generated by Django 4.2.10 on 2026-02-03 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_building_alter_room_room_number_bed_room_building_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='roomallocation',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='roomallocation',
            constraint=models.UniqueConstraint(condition=models.Q(('end_date__isnull', True)), fields=('student',), name='rooms_unique_active_allocation_per_student'),
        ),
        migrations.AddConstraint(
            model_name='roomallocation',
            constraint=models.UniqueConstraint(condition=models.Q(('end_date__isnull', True)), fields=('bed',), name='rooms_unique_active_allocation_per_bed'),
        ),
    ]
