# Generated by Django 4.2.27 on 2026-02-09 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_alter_roomallocation_unique_together_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='roomallocation',
            index=models.Index(fields=['student', 'end_date', 'status'], name='rooms_rooma_student_a516da_idx'),
        ),
        migrations.AddIndex(
            model_name='roomallocation',
            index=models.Index(fields=['room', 'end_date', 'status'], name='rooms_rooma_room_id_21c153_idx'),
        ),
        migrations.AddIndex(
            model_name='roomallocation',
            index=models.Index(fields=['bed', 'end_date'], name='rooms_rooma_bed_id_817528_idx'),
        ),
        migrations.AddIndex(
            model_name='roomallocation',
            index=models.Index(fields=['status', 'allocated_date'], name='rooms_rooma_status_13fc0f_idx'),
        ),
    ]
