# Generated by Django 4.2.27 on 2026-02-09 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_add_critical_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='bed_type',
            field=models.CharField(choices=[('standard', 'Standard Single'), ('bunk', 'Double Tier (Bunk)')], default='standard', max_length=20),
        ),
    ]
