# Generated by Django 4.2.27 on 2026-02-09 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_room_bed_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='bed_type',
            field=models.CharField(choices=[('standard', 'Standard Single'), ('bunk', 'Double Tier (Bunk)'), ('combined', 'Combined (Mixed)')], default='standard', max_length=20),
        ),
    ]
