# Generated by Django 4.2.10 on 2026-02-12 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0008_add_partial_index'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='roomallocation',
            name='idx_active_allocations',
        ),
    ]
