# Generated by Django 4.2.10 on 2026-02-16 18:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rooms', '0009_remove_roomallocation_idx_active_allocations'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomAllocationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('action', models.CharField(choices=[('allocated', 'Allocated'), ('deallocated', 'Deallocated'), ('moved', 'Moved')], max_length=20)),
                ('details', models.TextField(blank=True, help_text='Details of the change.')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='room',
            name='notes',
            field=models.TextField(blank=True, help_text='Administrative notes for the room.'),
        ),
        migrations.AddField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('full', 'Full'), ('under_maintenance', 'Under Maintenance')], default='available', max_length=20),
        ),
        migrations.AddField(
            model_name='roomallocation',
            name='allocated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocations_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['status'], name='rooms_room_status_19affd_idx'),
        ),
        migrations.AddField(
            model_name='roomallocationhistory',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_changes_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='roomallocationhistory',
            name='from_bed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_from', to='rooms.bed'),
        ),
        migrations.AddField(
            model_name='roomallocationhistory',
            name='from_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_from', to='rooms.room'),
        ),
        migrations.AddField(
            model_name='roomallocationhistory',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='roomallocationhistory',
            name='to_bed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_to', to='rooms.bed'),
        ),
        migrations.AddField(
            model_name='roomallocationhistory',
            name='to_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_to', to='rooms.room'),
        ),
    ]
