# Generated by Django 4.2.10 on 2026-02-26 02:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0010_roomallocationhistory_room_notes_room_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="double_beds",
            field=models.IntegerField(
                default=0, help_text="Number of double/bunk beds in the room"
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="single_beds",
            field=models.IntegerField(
                default=0, help_text="Number of single beds in the room"
            ),
        ),
    ]
