# Generated by Django 4.2.10 on 2026-02-27 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0011_room_double_beds_room_single_beds'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='attendance_taker_role',
            field=models.CharField(choices=[('warden', 'Warden'), ('staff', 'Staff / HR'), ('both', 'Warden or HR')], default='warden', help_text='Who is responsible for taking attendance for this block.', max_length=50),
        ),
        migrations.AddField(
            model_name='building',
            name='attendance_time',
            field=models.TimeField(blank=True, help_text='Time when attendance must be taken.', null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='gender_type',
            field=models.CharField(choices=[('boys', 'Boys'), ('girls', 'Girls'), ('co-ed', 'Co-Ed')], default='co-ed', help_text='Gender restriction for this block.', max_length=10),
        ),
        migrations.AddField(
            model_name='building',
            name='lunch_time_end',
            field=models.TimeField(blank=True, help_text='End time for lunch.', null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='lunch_time_start',
            field=models.TimeField(blank=True, help_text='Start time for lunch.', null=True),
        ),
    ]
