# Generated by Django 4.2.10 on 2026-03-01 01:43 (perf_indexes_phase1 - fixed for SQLite compat)

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0012_building_attendance_taker_role_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='room',
            new_name='room_floor_num_idx',
            old_name='rooms_room_floor_2bccb4_idx',
        ),
        migrations.RenameIndex(
            model_name='room',
            new_name='room_available_idx',
            old_name='rooms_room_is_avai_ad8094_idx',
        ),
        migrations.RenameIndex(
            model_name='room',
            new_name='room_status_idx',
            old_name='rooms_room_status_19affd_idx',
        ),
        migrations.RenameIndex(
            model_name='roomallocation',
            new_name='alloc_student_active_idx',
            old_name='rooms_rooma_student_a516da_idx',
        ),
        migrations.RenameIndex(
            model_name='roomallocation',
            new_name='alloc_room_active_idx',
            old_name='rooms_rooma_room_id_21c153_idx',
        ),
        migrations.RenameIndex(
            model_name='roomallocation',
            new_name='alloc_bed_active_idx',
            old_name='rooms_rooma_bed_id_817528_idx',
        ),
        migrations.RenameIndex(
            model_name='roomallocation',
            new_name='alloc_status_date_idx',
            old_name='rooms_rooma_status_13fc0f_idx',
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['building', 'floor'], name='room_building_floor_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['building', 'is_available', 'status'], name='room_avail_status_idx'),
        ),
        # Partial index using AddIndex (not AddConstraint) for SQLite compatibility
        migrations.AddIndex(
            model_name='roomallocation',
            index=models.Index(
                condition=models.Q(end_date__isnull=True, status='approved'),
                fields=['student', 'room'],
                name='alloc_active_student_room_idx',
            ),
        ),
    ]
