# Generated by Django 4.2.10 on 2026-03-01 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0014_perf_indexes_fix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='bed_type',
            field=models.CharField(choices=[('single', 'Single'), ('double', 'Double'), ('custom', 'Custom')], default='single', max_length=20),
        ),
    ]
