# Generated by Django 4.2.10 on 2026-03-04 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0015_alter_room_bed_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='disabled_reason',
            field=models.CharField(blank=True, default='', help_text='Optional message shown to users when their hostel is disabled.', max_length=500),
        ),
        migrations.AddField(
            model_name='building',
            name='is_active',
            field=models.BooleanField(default=True, help_text='When disabled, all students in this hostel are locked out of the system.'),
        ),
    ]
