# Generated by Django 4.2.10 on 2026-03-04 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0002_add_college_active_toggle'),
        ('rooms', '0016_add_building_active_toggle'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='disabled_floors',
            field=models.JSONField(blank=True, default=list, help_text='List of floor numbers that are currently disabled for students.'),
        ),
        migrations.AlterField(
            model_name='building',
            name='disabled_reason',
            field=models.CharField(blank=True, default='', help_text='Optional message shown to users when this block is disabled.', max_length=500),
        ),
        migrations.AlterField(
            model_name='building',
            name='is_active',
            field=models.BooleanField(default=True, help_text='When disabled, all students in this specific block are locked out.'),
        ),
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='When disabled, all students in all blocks of this hostel are locked out.')),
                ('disabled_reason', models.CharField(blank=True, default='', help_text='Optional message shown to users when their hostel is disabled.', max_length=500)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostels', to='colleges.college')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('college', 'name')},
            },
        ),
        migrations.AddField(
            model_name='building',
            name='hostel',
            field=models.ForeignKey(blank=True, help_text='The hostel this block belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='rooms.hostel'),
        ),
    ]
