# Generated by Django 4.2.10 on 2026-03-05 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0018_alter_bed_created_at_alter_bed_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='allow_student_complaints',
            field=models.BooleanField(default=False, help_text='If enabled, students in this building can raise complaints directly.'),
        ),
    ]
