# Generated by Django 4.2.10 on 2026-04-04 06:30

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0011_remove_college_deleted_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rooms', '0021_bed_college_bed_trace_id_building_college_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bed',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='building',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='hostel',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='room',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='roomallocation',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='roomallocationhistory',
            name='deleted_at',
        ),
        migrations.CreateModel(
            name='RoomRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trace_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Global Trace ID for request correlation.')),
                ('tenant_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('preferred_room_type', models.CharField(choices=[('single', 'Single'), ('double', 'Double'), ('triple', 'Triple'), ('quad', 'Quad'), ('dormitory', 'Dormitory')], max_length=20)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('college', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='colleges.college')),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_room_requests', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_requests', to=settings.AUTH_USER_MODEL)),
                ('target_bed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rooms.bed')),
                ('target_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_requests', to='rooms.room')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['student', 'status'], name='rooms_roomr_student_19cea4_idx'), models.Index(fields=['status', '-created_at'], name='rooms_roomr_status_b9dca7_idx')],
            },
            bases=(models.Model, core.models.AuditableModelMixin),
        ),
    ]
