# Generated by Django 4.2.10 on 2026-01-27 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('title', models.CharField(max_length=200)),
                ('report_type', models.CharField(choices=[('attendance', 'Attendance'), ('financial', 'Financial'), ('occupancy', 'Occupancy'), ('events', 'Events'), ('meals', 'Meals')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('data', models.JSONField(default=dict)),
                ('summary', models.TextField(blank=True)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reports_report',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['report_type', '-created_at'], name='reports_rep_report__6e1fe1_idx')],
            },
        ),
    ]
