# Generated by Django 4.2.10 on 2026-03-05 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_report_created_at_alter_report_deleted_at'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='report',
            new_name='report_type_created_idx',
            old_name='reports_rep_report__6e1fe1_idx',
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['generated_by', '-created_at'], name='report_user_created_idx'),
        ),
    ]
