# Generated by Django 4.2.10 on 2026-02-16 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_meal_attendance_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='feedback_prompt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='is_feedback_active',
            field=models.BooleanField(default=False),
        ),
    ]
