# Generated by Django 4.2.10 on 2026-02-16 01:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meals', '0003_meal_feedback_prompt_meal_is_feedback_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealSpecialRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('item_name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=1)),
                ('requested_for_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('delivered', 'Delivered'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Special instructions or extra text')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_for_date', '-created_at'],
            },
        ),
    ]
