# Generated by Django 4.2.10 on 2026-02-23 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0006_menunotification_deleted_at'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='meal',
            new_name='meals_meal_menu_po_5778fc_idx',
            old_name='meals_menu_posted_idx',
        ),
        migrations.RenameIndex(
            model_name='mealfeedback',
            new_name='meals_mealf_meal_id_d45207_idx',
            old_name='meal_feedback_type_idx',
        ),
        migrations.RenameIndex(
            model_name='mealfeedback',
            new_name='meals_mealf_is_publ_4ddc3c_idx',
            old_name='feedback_published_idx',
        ),
        migrations.RenameIndex(
            model_name='menunotification',
            new_name='meals_menun_menu_da_e94293_idx',
            old_name='menu_date_status_idx',
        ),
    ]
