# Generated by Django 4.2.10 on 2026-02-28 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0007_rename_meals_menu_posted_idx_meals_meal_menu_po_5778fc_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMealReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('date', models.DateField()),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snacks', 'Snacks')], max_length=20)),
                ('original_population', models.IntegerField(default=0)),
                ('adjusted_population', models.IntegerField(default=0)),
                ('excluded_count', models.IntegerField(default=0)),
                ('students_marked_absent', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-date', 'meal_type'],
                'indexes': [models.Index(fields=['-date', 'meal_type'], name='meals_daily_date_da207a_idx')],
                'unique_together': {('date', 'meal_type')},
            },
        ),
    ]
