# Generated by Django 4.2.10 on 2026-03-01 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0008_dailymealreport'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='meal',
            new_name='meal_date_idx',
            old_name='meals_meal_meal_da_a08af3_idx',
        ),
        migrations.RenameIndex(
            model_name='meal',
            new_name='meal_posted_idx',
            old_name='meals_meal_menu_po_5778fc_idx',
        ),
        migrations.AddIndex(
            model_name='meal',
            index=models.Index(fields=['meal_date', 'meal_type'], name='meal_date_type_idx'),
        ),
        migrations.AddIndex(
            model_name='mealattendance',
            index=models.Index(fields=['meal', 'status'], name='meal_att_meal_status_idx'),
        ),
        migrations.AddIndex(
            model_name='mealspecialrequest',
            index=models.Index(fields=['status', 'requested_for_date'], name='specreq_status_date_idx'),
        ),
        migrations.AddIndex(
            model_name='mealspecialrequest',
            index=models.Index(fields=['student', 'requested_for_date'], name='specreq_student_date_idx'),
        ),
    ]
