# Generated by Django 4.2.10 on 2026-03-07 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0010_alter_dailymealreport_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
