# Generated by Django 4.2.10 on 2026-03-30 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meals', '0011_meal_end_time_meal_start_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealFeedbackResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('comment', models.TextField(blank=True)),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='meals.mealfeedback')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('feedback', 'student')},
            },
        ),
        migrations.CreateModel(
            name='MealWastage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('waste_weight_kg', models.DecimalField(decimal_places=2, help_text='Weight of food wasted in KG', max_digits=10)),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=0, help_text='Estimated cost of wasted food', max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wastage', to='meals.meal')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wastage_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Meal Wastage Records',
                'ordering': ['-meal__meal_date'],
            },
        ),
        migrations.DeleteModel(
            name='DailyMealReport',
        ),
    ]
