# Generated by Django 4.2.10 on 2026-03-31 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("colleges", "0008_collegepolicy"),
        ("meals", "0012_mealfeedbackresponse_mealwastage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="meal",
            name="college",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_records",
                to="colleges.college",
            ),
        ),
        migrations.AddField(
            model_name="mealattendance",
            name="college",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_records",
                to="colleges.college",
            ),
        ),
        migrations.AddField(
            model_name="mealpreference",
            name="college",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_records",
                to="colleges.college",
            ),
        ),
        migrations.AddField(
            model_name="mealspecialrequest",
            name="college",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_records",
                to="colleges.college",
            ),
        ),
        migrations.AddField(
            model_name="mealwastage",
            name="college",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_records",
                to="colleges.college",
            ),
        ),
        migrations.AddField(
            model_name="menunotification",
            name="college",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_records",
                to="colleges.college",
            ),
        ),
    ]
