# Generated by Django 4.2.10 on 2026-04-01 02:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0010_college_trace_id_collegepolicy_trace_id_and_more'),
        ('meals', '0014_meal_is_deleted_meal_tenant_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='trace_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Global Trace ID for request correlation.'),
        ),
        migrations.AddField(
            model_name='mealattendance',
            name='trace_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Global Trace ID for request correlation.'),
        ),
        migrations.AddField(
            model_name='mealfeedback',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='colleges.college'),
        ),
        migrations.AddField(
            model_name='mealfeedback',
            name='trace_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Global Trace ID for request correlation.'),
        ),
        migrations.AddField(
            model_name='mealfeedbackresponse',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='colleges.college'),
        ),
        migrations.AddField(
            model_name='mealfeedbackresponse',
            name='trace_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Global Trace ID for request correlation.'),
        ),
        migrations.AddField(
            model_name='mealitem',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='colleges.college'),
        ),
        migrations.AddField(
            model_name='mealitem',
            name='trace_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Global Trace ID for request correlation.'),
        ),
        migrations.AddField(
            model_name='mealpreference',
            name='trace_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Global Trace ID for request correlation.'),
        ),
        migrations.AddField(
            model_name='mealspecialrequest',
            name='trace_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Global Trace ID for request correlation.'),
        ),
        migrations.AddField(
            model_name='mealwastage',
            name='trace_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Global Trace ID for request correlation.'),
        ),
        migrations.AddField(
            model_name='menunotification',
            name='trace_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Global Trace ID for request correlation.'),
        ),
        migrations.AddIndex(
            model_name='meal',
            index=models.Index(fields=['tenant_id', 'meal_date'], name='meal_tenant_date_idx'),
        ),
        migrations.AddIndex(
            model_name='mealattendance',
            index=models.Index(fields=['tenant_id', 'status'], name='meal_att_tenant_status_idx'),
        ),
    ]
