# Generated by Django 4.2.10 on 2026-04-04 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0015_meal_trace_id_mealattendance_trace_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='mealattendance',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='mealfeedback',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='mealfeedbackresponse',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='mealitem',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='mealpreference',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='mealspecialrequest',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='mealwastage',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='menunotification',
            name='deleted_at',
        ),
    ]
