# Generated by Django 4.2.10 on 2026-04-06 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0016_remove_meal_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='mealfeedback',
            constraint=models.CheckConstraint(check=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='meal_feedback_rating_between_1_5'),
        ),
        migrations.AddConstraint(
            model_name='mealfeedbackresponse',
            constraint=models.CheckConstraint(check=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='meal_feedback_response_rating_between_1_5'),
        ),
    ]
