# Generated by Django 4.2.10 on 2026-02-07 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostelconnect_auth', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['phone_number'], name='hostelconne_phone_n_bff5f1_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='hostelconne_role_6fc01d_idx'),
        ),
    ]
