# Generated by Django 4.2.27 on 2026-02-11 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostelconnect_auth', '0004_user_hostelconne_phone_n_bff5f1_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_password_changed',
            field=models.BooleanField(default=False),
        ),
    ]
