# Generated by Django 4.2.10 on 2026-03-01 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostelconnect_auth', '0007_user_assigned_blocks_user_assigned_floors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='custom_location',
            field=models.CharField(blank=True, help_text='Custom location if not in a specific block (e.g., Rehab)', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='is_on_campus',
            field=models.BooleanField(default=False, help_text='Designates if this person is staying on campus'),
        ),
    ]
