# Generated by Django 4.2.10 on 2026-03-02 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0001_initial'),
        ('hostelconnect_auth', '0008_user_custom_location_user_is_on_campus'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='colleges.college'),
        ),
    ]
