# Generated by Django 4.2.10 on 2026-03-04 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostelconnect_auth', '0010_user_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='hostelconne_email_afb4c6_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['registration_number'], name='hostelconne_registr_5e1a30_idx'),
        ),
    ]
