# Generated by Django 4.2.10 on 2026-03-08 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostelconnect_auth', '0011_alter_user_created_at_alter_user_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role', 'is_active'], name='hostelconne_role_242f53_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['-created_at'], name='hostelconne_created_938031_idx'),
        ),
    ]
