# Generated by Django 4.2.10 on 2026-03-13 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0019_building_allow_student_complaints"),
        ("hostelconnect_auth", "0013_user_student_type_alter_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="department",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="user",
            name="hostel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="rooms.hostel",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("student", "Student"),
                    ("staff", "Staff"),
                    ("admin", "Admin"),
                    ("super_admin", "Super Admin"),
                    ("principal", "Principal"),
                    ("director", "Director"),
                    ("hod", "HOD"),
                    ("head_warden", "Head Warden"),
                    ("warden", "Warden"),
                    ("incharge", "Incharge"),
                    ("chef", "Chef"),
                    ("head_chef", "Head Chef"),
                    ("gate_security", "Gate Security"),
                    ("security_head", "Security Head"),
                    ("hr", "HR Rep"),
                    ("pd", "Physical Director"),
                    ("pt", "Physical Trainer"),
                ],
                default="student",
                max_length=20,
            ),
        ),
    ]
