# Generated by Django 4.2.10 on 2026-03-31 11:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hostelconnect_auth", "0014_user_department_user_hostel_alter_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="semester",
            field=models.PositiveSmallIntegerField(
                blank=True, help_text="Current semester (1-10)", null=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="year",
            field=models.PositiveSmallIntegerField(
                blank=True, help_text="Current year of study (1-5)", null=True
            ),
        ),
    ]
