# Generated by Django 4.2.10 on 2026-03-31 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostelconnect_auth', '0016_user_late_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('staff', 'Staff'), ('admin', 'Admin'), ('super_admin', 'Super Admin'), ('principal', 'Principal'), ('director', 'Director'), ('hod', 'HOD'), ('head_warden', 'Head Warden'), ('warden', 'Warden'), ('incharge', 'Incharge'), ('chef', 'Chef'), ('head_chef', 'Head Chef'), ('gate_security', 'Gate Security'), ('security_head', 'Security Head'), ('hr', 'HR Rep'), ('pd', 'Physical Director'), ('pt', 'Physical Trainer'), ('alumni', 'Alumni')], default='student', max_length=20),
        ),
    ]
