# Generated by Django 4.2.10 on 2026-04-01 02:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hostelconnect_auth', '0018_user_is_deleted_user_tenant_id_alter_user_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='trace_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Global Trace ID for request correlation.'),
        ),
    ]
