# Generated by Django 4.2.10 on 2026-04-04 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostelconnect_auth', '0019_user_trace_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='deleted_at',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_password_changed',
            field=models.BooleanField(default=True),
        ),
    ]
