# Generated by Django 4.2.10 on 2026-04-05 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostelconnect_auth', '0020_remove_user_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_access_all_blocks',
            field=models.BooleanField(default=False, help_text='If enabled by Head Warden/Admin, this user can access all blocks in their college.'),
        ),
    ]
