# Generated by Django 4.2.10 on 2026-04-12 17:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hostelconnect_auth', '0022_user_college_role_active_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='trace_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Stable institutional trace / correlation id (also usable on ID surfaces).'),
        ),
    ]
