# Generated by Django 4.2.10 on 2026-04-14 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0022_remove_bed_deleted_at_remove_building_deleted_at_and_more'),
        ('hostelconnect_auth', '0023_alter_user_trace_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assigned_hostels',
            field=models.ManyToManyField(blank=True, related_name='assigned_staff', to='rooms.hostel'),
        ),
    ]
