# Generated by Django 4.2.10 on 2026-04-14 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gate_passes', '0029_gatelocation_gatelocation_gate_loc_college_name_uniq_and_more'),
        ('hostelconnect_auth', '0025_user_assigned_floors_by_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assigned_gate_locations',
            field=models.ManyToManyField(blank=True, related_name='assigned_security_users', to='gate_passes.gatelocation'),
        ),
    ]
