# Generated by Django 4.2.10 on 2026-03-31 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlumniProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('graduation_year', models.PositiveIntegerField()),
                ('department', models.CharField(max_length=100)),
                ('current_company', models.CharField(blank=True, max_length=200)),
                ('job_role', models.CharField(blank=True, max_length=150)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('linkedin', models.URLField(blank=True)),
                ('achievements', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_mentor', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alumni_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'alumni_profile',
                'ordering': ['-graduation_year'],
            },
        ),
        migrations.CreateModel(
            name='Mentorship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('topic', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('closed', 'Closed')], default='requested', max_length=20)),
                ('mentor_notes', models.TextField(blank=True)),
                ('student_notes', models.TextField(blank=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentoring_relationships', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_relationships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'alumni_mentorship',
                'unique_together': {('mentor', 'student')},
            },
        ),
    ]
