# Generated by Django 4.2.10 on 2026-04-01 02:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0010_college_trace_id_collegepolicy_trace_id_and_more'),
        ('alumni', '0002_alumniprofile_is_deleted_alumniprofile_tenant_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumniprofile',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='colleges.college'),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='trace_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Global Trace ID for request correlation.'),
        ),
        migrations.AddField(
            model_name='mentorship',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='colleges.college'),
        ),
        migrations.AddField(
            model_name='mentorship',
            name='trace_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Global Trace ID for request correlation.'),
        ),
        migrations.AddIndex(
            model_name='alumniprofile',
            index=models.Index(fields=['tenant_id', 'graduation_year'], name='alumni_prof_tenant__e7e0d2_idx'),
        ),
        migrations.AddIndex(
            model_name='alumniprofile',
            index=models.Index(fields=['tenant_id', '-created_at'], name='alumni_tenant_created_idx'),
        ),
        migrations.AddIndex(
            model_name='mentorship',
            index=models.Index(fields=['tenant_id', 'status'], name='mentor_tenant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='mentorship',
            index=models.Index(fields=['tenant_id', '-created_at'], name='mentor_tenant_created_idx'),
        ),
    ]
