# Generated by Django 4.2.10 on 2026-04-04 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0003_alumniprofile_college_alumniprofile_trace_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumniprofile',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='mentorship',
            name='deleted_at',
        ),
    ]
