# Generated by Django 4.2.10 on 2026-03-31 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('colleges', '0008_collegepolicy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('key', models.CharField(help_text='Config identifier (e.g. SLA_HOURS_COMPLAINT)', max_length=100, unique=True)),
                ('value', models.JSONField(help_text='Standardized value — string, number, or object')),
                ('description', models.TextField(blank=True)),
                ('college', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='configs', to='colleges.college')),
            ],
            options={
                'verbose_name': 'System Configuration',
                'db_table': 'ops_system_config',
            },
        ),
        migrations.CreateModel(
            name='BulkUserJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('file_name', models.CharField(max_length=255)),
                ('total_rows', models.IntegerField(default=0)),
                ('success_count', models.IntegerField(default=0)),
                ('failure_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_log', models.JSONField(blank=True, default=list, help_text='List of errors per row')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulk_jobs', to='colleges.college')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulk_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ops_bulk_job',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('action', models.CharField(help_text='e.g. ROLE_CHANGE, BULK_UPLOAD, CONFIG_UPDATE', max_length=50)),
                ('entity_type', models.CharField(max_length=100)),
                ('entity_id', models.CharField(max_length=100)),
                ('before_state', models.JSONField(blank=True, null=True)),
                ('after_state', models.JSONField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ops_audit_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ops_audit_action',
                'ordering': ['-created_at'],
            },
        ),
    ]
