# Generated by Django 4.2.10 on 2026-04-01 02:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_auditaction_is_deleted_auditaction_tenant_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditaction',
            name='trace_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Global Trace ID for request correlation.'),
        ),
        migrations.AddField(
            model_name='bulkuserjob',
            name='trace_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Global Trace ID for request correlation.'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='trace_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Global Trace ID for request correlation.'),
        ),
    ]
