# Generated by Django 4.2.10 on 2026-04-04 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_auditaction_trace_id_bulkuserjob_trace_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditaction',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='bulkuserjob',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='systemconfig',
            name='deleted_at',
        ),
    ]
