# Generated by Django 4.2.10 on 2026-03-04 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='disabled_reason',
            field=models.CharField(blank=True, default='', help_text='Optional message shown to users when their college is disabled.', max_length=500),
        ),
        migrations.AddField(
            model_name='college',
            name='is_active',
            field=models.BooleanField(default=True, help_text='When disabled, all users of this college are locked out of the system.'),
        ),
    ]
