# Generated by Django 4.2.10 on 2026-03-20 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0005_collegemoduleconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegemoduleconfig',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
