# Generated by Django 4.2.10 on 2026-03-30 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0006_alter_collegemoduleconfig_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('name', models.CharField(help_text="e.g. 'College Official Website'", max_length=100)),
                ('api_key_hash', models.CharField(max_length=255, unique=True)),
                ('webhook_url', models.URLField(blank=True, help_text='URL to notify on campus events.', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'colleges_integration',
            },
        ),
        migrations.AddField(
            model_name='college',
            name='current_storage_bytes',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='college',
            name='has_api_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='college',
            name='is_whitelabel_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='college',
            name='max_monthly_emails',
            field=models.PositiveIntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='college',
            name='max_monthly_sms',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='college',
            name='max_storage_mib',
            field=models.PositiveIntegerField(default=500, help_text='Storage limit in MiB.'),
        ),
        migrations.AddField(
            model_name='college',
            name='trial_ends_at',
            field=models.DateTimeField(blank=True, help_text='End of free trial period.', null=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='subscription_status',
            field=models.CharField(choices=[('free', 'Free'), ('starter', 'Starter'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], db_index=True, default='free', help_text='SaaS subscription tier for this college.', max_length=20),
        ),
        migrations.AddIndex(
            model_name='college',
            index=models.Index(fields=['is_active', 'subscription_status'], name='colleges_co_is_acti_b14eb5_idx'),
        ),
        migrations.AddIndex(
            model_name='college',
            index=models.Index(fields=['code'], name='colleges_co_code_113ab7_idx'),
        ),
        migrations.AddField(
            model_name='externalintegration',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to='colleges.college'),
        ),
        migrations.AlterUniqueTogether(
            name='externalintegration',
            unique_together={('college', 'name')},
        ),
    ]
