# Generated by Django 4.2.10 on 2026-03-31 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("colleges", "0007_externalintegration_college_current_storage_bytes_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CollegePolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, db_index=True, default=None, null=True
                    ),
                ),
                (
                    "gatepass_auto_expire_hours",
                    models.PositiveIntegerField(
                        default=24,
                        help_text="Hours after which an exit becomes an auto-late return.",
                    ),
                ),
                (
                    "gatepass_late_fine_per_hour",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "attendance_reporting_time",
                    models.TimeField(
                        blank=True,
                        help_text="Time to auto-generate absence alerts.",
                        null=True,
                    ),
                ),
                ("emergency_contact_required", models.BooleanField(default=True)),
                (
                    "college",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="policy",
                        to="colleges.college",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "College Policies",
                "db_table": "colleges_policy",
            },
        ),
    ]
