# Generated by Django 4.2.10 on 2026-03-31 13:24

from django.db import migrations, models
import uuid


def _alter_pk_to_uuid_postgres(schema_editor, table_name):
    if schema_editor.connection.vendor != 'postgresql':
        return

    quote = schema_editor.quote_name
    fk_rows = []
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            """
            SELECT tc.table_name, kcu.column_name, tc.constraint_name
            FROM information_schema.table_constraints tc
            JOIN information_schema.key_column_usage kcu
              ON tc.constraint_name = kcu.constraint_name
             AND tc.table_schema = kcu.table_schema
            JOIN information_schema.constraint_column_usage ccu
              ON ccu.constraint_name = tc.constraint_name
             AND ccu.table_schema = tc.table_schema
            WHERE tc.constraint_type = 'FOREIGN KEY'
              AND tc.table_schema = 'public'
              AND ccu.table_name = %s
              AND ccu.column_name = 'id'
            ORDER BY tc.table_name, kcu.column_name
            """,
            [table_name],
        )
        fk_rows = cursor.fetchall()

        constraints = []
        for fk_table, fk_column, constraint_name in fk_rows:
            cursor.execute(
                """
                SELECT pg_get_constraintdef(c.oid)
                FROM pg_constraint c
                JOIN pg_class t ON t.oid = c.conrelid
                JOIN pg_namespace n ON n.oid = t.relnamespace
                WHERE n.nspname = 'public'
                  AND t.relname = %s
                  AND c.conname = %s
                """,
                [fk_table, constraint_name],
            )
            row = cursor.fetchone()
            if row:
                constraints.append((fk_table, fk_column, constraint_name, row[0]))

    handled_columns = set()
    for fk_table, fk_column, constraint_name, _ in constraints:
        schema_editor.execute(
            f'ALTER TABLE {quote(fk_table)} DROP CONSTRAINT {quote(constraint_name)}'
        )
        if (fk_table, fk_column) in handled_columns:
            continue
        schema_editor.execute(
            f'ALTER TABLE {quote(fk_table)} ALTER COLUMN {quote(fk_column)} '
            f'TYPE uuid USING md5({quote(fk_column)}::text)::uuid'
        )
        handled_columns.add((fk_table, fk_column))

    schema_editor.execute(
        f'ALTER TABLE {quote(table_name)} ALTER COLUMN "id" DROP IDENTITY IF EXISTS'
    )
    schema_editor.execute(
        f'ALTER TABLE {quote(table_name)} ALTER COLUMN "id" DROP DEFAULT'
    )
    schema_editor.execute(
        f'ALTER TABLE {quote(table_name)} ALTER COLUMN "id" TYPE uuid USING md5("id"::text)::uuid'
    )

    for fk_table, _, constraint_name, constraint_def in constraints:
        schema_editor.execute(
            f'ALTER TABLE {quote(fk_table)} ADD CONSTRAINT {quote(constraint_name)} {constraint_def}'
        )


def _convert_college_id(apps, schema_editor):
    _alter_pk_to_uuid_postgres(schema_editor, 'colleges_college')


def _convert_college_policy_id(apps, schema_editor):
    _alter_pk_to_uuid_postgres(schema_editor, 'colleges_policy')


def _convert_external_integration_id(apps, schema_editor):
    _alter_pk_to_uuid_postgres(schema_editor, 'colleges_integration')


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0008_collegepolicy'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='college',
            name='tenant_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='collegepolicy',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='collegepolicy',
            name='tenant_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='externalintegration',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='externalintegration',
            name='tenant_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='collegepolicy',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='externalintegration',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(_convert_college_id, migrations.RunPython.noop),
                migrations.RunPython(_convert_college_policy_id, migrations.RunPython.noop),
                migrations.RunPython(_convert_external_integration_id, migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name='college',
                    name='id',
                    field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                migrations.AlterField(
                    model_name='collegepolicy',
                    name='id',
                    field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                migrations.AlterField(
                    model_name='externalintegration',
                    name='id',
                    field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
            ],
        ),
    ]
