# Generated by Django 4.2.10 on 2026-04-04 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0010_college_trace_id_collegepolicy_trace_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='college',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='collegepolicy',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='externalintegration',
            name='deleted_at',
        ),
    ]
