# Generated by Django 4.2.10 on 2026-04-14 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0011_remove_college_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='attendance_end_time',
            field=models.TimeField(blank=True, help_text='Standard daily end time for warden attendance checks (e.g., 22:30).', null=True),
        ),
        migrations.AddField(
            model_name='college',
            name='attendance_start_time',
            field=models.TimeField(blank=True, help_text='Standard daily start time for warden attendance checks (e.g., 21:00).', null=True),
        ),
    ]
