# Generated by Django 4.2.10 on 2026-04-04 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0004_application_college_application_trace_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='company',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='jobposting',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='deleted_at',
        ),
    ]
