# Generated by Django 4.2.10 on 2026-01-27 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GateScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('direction', models.CharField(choices=[('in', 'Entry'), ('out', 'Exit')], max_length=10)),
                ('scan_time', models.DateTimeField(auto_now_add=True)),
                ('qr_code', models.CharField(max_length=500)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('verified', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'gate_scans_gatescan',
                'ordering': ['-scan_time'],
            },
        ),
    ]
