# Generated by Django 4.2.10 on 2026-01-27 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gate_scans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gatescan',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gate_scans_log', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='gatescan',
            index=models.Index(fields=['student', '-scan_time'], name='gate_scans__student_c3529b_idx'),
        ),
    ]
