# Generated by Django 4.2.10 on 2026-03-05 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gate_scans', '0003_alter_gatescan_created_at_alter_gatescan_deleted_at'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='gatescan',
            new_name='gsc_student_time_idx',
            old_name='gate_scans__student_c3529b_idx',
        ),
        migrations.AddIndex(
            model_name='gatescan',
            index=models.Index(fields=['direction', '-scan_time'], name='gsc_direction_time_idx'),
        ),
        migrations.AddIndex(
            model_name='gatescan',
            index=models.Index(fields=['verified', '-scan_time'], name='gsc_verified_time_idx'),
        ),
    ]
