# Generated by Django 4.2.10 on 2026-03-13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gate_scans', '0004_add_performance_indexes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GateScan',
        ),
    ]
