# Generated by Django 4.2.10 on 2026-02-16 18:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('leave_type', models.CharField(choices=[('sick', 'Sick Leave'), ('personal', 'Personal Leave'), ('vacation', 'Vacation'), ('emergency', 'Emergency Leave'), ('academic', 'Academic Leave'), ('family', 'Family Event')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('parent_informed', models.BooleanField(default=False, help_text='Whether parent/guardian has been informed')),
                ('parent_contact', models.CharField(blank=True, help_text='Parent contact number', max_length=15)),
                ('destination', models.CharField(blank=True, help_text='Where the student will go', max_length=255)),
                ('contact_during_leave', models.CharField(blank=True, help_text='Contact number during leave', max_length=15)),
                ('attachment_url', models.URLField(blank=True, help_text='URL for supporting document')),
                ('notes', models.TextField(blank=True, help_text='Additional notes from student or approver')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leaves_approved', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='leave_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['student', 'status'], name='leaves_leav_student_a9a28f_idx'), models.Index(fields=['status', 'start_date'], name='leaves_leav_status_fe2f1c_idx'), models.Index(fields=['start_date', 'end_date'], name='leaves_leav_start_d_352125_idx')],
            },
        ),
    ]
