# Generated by Django 4.2.10 on 2026-03-20 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0005_backfill_leave_college'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='leaveapplication',
            name='leave_college_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='leaveapplication',
            name='leave_college_created_idx',
        ),
    ]
