# Generated by Django 4.2.10 on 2026-04-06 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0008_remove_leaveapplication_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='leaveapplication',
            constraint=models.CheckConstraint(check=models.Q(('end_date__gte', models.F('start_date'))), name='leave_application_end_date_gte_start_date'),
        ),
    ]
