# Generated by Django 4.2.10 on 2026-04-12 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0009_leaveapplication_leave_application_end_date_gte_start_date'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='leaveapplication',
            index=models.Index(fields=['tenant_id', 'status'], name='leave_tenant_status_idx'),
        ),
    ]
