# Generated by Django 4.2.10 on 2026-01-27 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('metric_type', models.CharField(choices=[('occupancy', 'Occupancy Rate'), ('attendance', 'Attendance Rate'), ('meal_satisfaction', 'Meal Satisfaction'), ('api_response_time', 'API Response Time'), ('active_users', 'Active Users')], max_length=50)),
                ('value', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'metrics_metric',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['metric_type', '-timestamp'], name='metrics_met_metric__f4967a_idx')],
            },
        ),
    ]
