# Generated by Django 4.2.27 on 2026-02-09 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='category',
            field=models.CharField(choices=[('electrical', 'Electrical'), ('plumbing', 'Plumbing'), ('carpentry', 'Carpentry'), ('cleaning', 'Cleaning'), ('internet', 'Internet'), ('mess', 'Mess/Food'), ('other', 'Other')], max_length=50),
        ),
    ]
