# Generated by Django 4.2.10 on 2026-03-08 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0003_alter_complaint_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complaint',
            options={'ordering': ['severity', '-created_at']},
        ),
        migrations.AlterField(
            model_name='complaint',
            name='severity',
            field=models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='low', max_length=20),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['category'], name='complaints__categor_8115a1_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['is_overdue'], name='complaints__is_over_e9225a_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['-created_at'], name='complaints__created_a26128_idx'),
        ),
    ]
