# Generated by Django 4.2.10 on 2026-03-30 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0007_remove_complaint_complaint_college_status_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complaint',
            options={'ordering': ['-created_at']},
        ),
    ]
