# Generated by Django 4.2.10 on 2026-03-31 11:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("complaints", "0008_fix_complaint_ordering"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComplaintUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, db_index=True, default=None, null=True
                    ),
                ),
                ("status_from", models.CharField(max_length=20)),
                ("status_to", models.CharField(max_length=20)),
                ("comment", models.TextField()),
                ("is_internal", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "complaint_updates",
                "ordering": ["created_at"],
            },
        ),
        migrations.RemoveIndex(
            model_name="complaint",
            name="complaints__status_3e08b4_idx",
        ),
        migrations.RemoveField(
            model_name="complaint",
            name="severity",
        ),
        migrations.AddField(
            model_name="complaint",
            name="escalation_level",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="complaint",
            name="expected_resolution_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="complaint",
            name="priority",
            field=models.CharField(
                choices=[
                    ("1", "Urgent (SLA Trigger)"),
                    ("2", "High"),
                    ("3", "Medium"),
                    ("4", "Low"),
                ],
                default="3",
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="complaint",
            name="student_type",
            field=models.CharField(
                choices=[("hosteller", "Hosteller"), ("day_scholar", "Day Scholar")],
                default="hosteller",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="complaint",
            name="subcategory",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="complaint",
            name="category",
            field=models.CharField(
                choices=[
                    ("room", "Room Issue"),
                    ("electrical", "Electrical"),
                    ("plumbing", "Plumbing"),
                    ("mess", "Mess/Food"),
                    ("cleaning", "Cleanliness"),
                    ("academic", "Academic"),
                    ("faculty", "Faculty"),
                    ("admin", "Admin"),
                    ("other", "Other"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="complaint",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("assigned", "Assigned"),
                    ("in_progress", "In Progress"),
                    ("resolved", "Resolved"),
                    ("closed", "Closed"),
                    ("reopened", "Reopened"),
                ],
                default="open",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="complaint",
            index=models.Index(
                fields=["status", "priority"], name="complaints__status_4fcfa3_idx"
            ),
        ),
        migrations.AddField(
            model_name="complaintupdate",
            name="complaint",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="updates",
                to="complaints.complaint",
            ),
        ),
        migrations.AddField(
            model_name="complaintupdate",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
