# Generated by Django 4.2.10 on 2026-04-04 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0011_complaint_trace_id_complaintupdate_college_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='complaintupdate',
            name='deleted_at',
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('procurement', 'Procurement'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('reopened', 'Reopened'), ('invalid', 'Invalid/Fake')], default='open', max_length=20),
        ),
    ]
