# Generated by Django 4.2.10 on 2026-04-07 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0012_remove_complaint_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='allow_room_entry',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='complaint',
            name='contact_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='complaint',
            name='location_details',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='complaint',
            name='preferred_visit_slot',
            field=models.CharField(choices=[('anytime', 'Anytime'), ('morning', 'Morning (6 AM - 12 PM)'), ('afternoon', 'Afternoon (12 PM - 5 PM)'), ('evening', 'Evening (5 PM - 10 PM)')], default='anytime', max_length=20),
        ),
    ]
