# Generated by Django 4.2.10 on 2026-03-31 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('colleges', '0008_collegepolicy'),
    ]

    operations = [
        migrations.CreateModel(
            name='SportFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('capacity', models.PositiveIntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sport_facilities_v2', to='colleges.college')),
            ],
            options={
                'verbose_name_plural': 'Sport Facilities',
                'db_table': 'sports_facility_v2',
            },
        ),
        migrations.CreateModel(
            name='SportsMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('title', models.CharField(max_length=150)),
                ('teams', models.JSONField(default=dict, help_text="{'team_a': 'Name', 'team_b': 'Name'}")),
                ('scheduled_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('ongoing', 'Ongoing'), ('completed', 'Completed')], default='scheduled', max_length=20)),
                ('score', models.JSONField(default=dict, help_text="{'team_a': 0, 'team_b': 0}")),
                ('winner', models.CharField(blank=True, max_length=100)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='sports.sportfacility')),
                ('organizer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organized_matches_v2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Sports Matches',
                'db_table': 'sports_match_v2',
                'ordering': ['-scheduled_time'],
            },
        ),
        migrations.CreateModel(
            name='SportBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('booked', 'Booked'), ('cancelled', 'Cancelled')], default='booked', max_length=20)),
                ('booked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sport_bookings_v2', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='sports.sportfacility')),
            ],
            options={
                'db_table': 'sports_booking_v2',
                'ordering': ['-start_time'],
            },
        ),
    ]
