# Generated by Django 4.2.10 on 2026-03-14 02:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sports", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sportbooking",
            name="scan_method",
            field=models.CharField(
                choices=[("qr", "QR Code"), ("manual", "Manual Entry")],
                default="qr",
                max_length=10,
            ),
        ),
    ]
