# Generated by Django 4.2.10 on 2026-04-01 02:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0010_college_trace_id_collegepolicy_trace_id_and_more'),
        ('sports', '0002_sportbooking_is_deleted_sportbooking_tenant_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportbooking',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='colleges.college'),
        ),
        migrations.AddField(
            model_name='sportbooking',
            name='trace_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Global Trace ID for request correlation.'),
        ),
        migrations.AddField(
            model_name='sportfacility',
            name='trace_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Global Trace ID for request correlation.'),
        ),
        migrations.AddField(
            model_name='sportsmatch',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='colleges.college'),
        ),
        migrations.AddField(
            model_name='sportsmatch',
            name='trace_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Global Trace ID for request correlation.'),
        ),
        migrations.AlterField(
            model_name='sportfacility',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='colleges.college'),
        ),
        migrations.AddIndex(
            model_name='sportbooking',
            index=models.Index(fields=['tenant_id', 'status'], name='spbook_tenant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='sportbooking',
            index=models.Index(fields=['tenant_id', '-created_at'], name='spbook_tenant_created_idx'),
        ),
        migrations.AddIndex(
            model_name='sportsmatch',
            index=models.Index(fields=['tenant_id', 'status'], name='spmatch_tenant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='sportsmatch',
            index=models.Index(fields=['tenant_id', '-created_at'], name='spmatch_tenant_created_idx'),
        ),
    ]
