# Generated by Django 4.2.10 on 2026-04-03 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0003_sportbooking_college_sportbooking_trace_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sportbooking',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='sportfacility',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='sportsmatch',
            name='deleted_at',
        ),
        migrations.AlterField(
            model_name='sportbooking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
