# Generated by Django 4.2.10 on 2026-03-20 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0004_backfill_sportbooking_college'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='sportbooking',
            name='sb_college_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='sportbooking',
            name='sb_college_created_idx',
        ),
    ]
