# Generated by Django 4.2.10 on 2026-04-04 12:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('colleges', '0011_remove_college_deleted_at_and_more'),
        ('sports', '0004_remove_sportbooking_deleted_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourtSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('max_players', models.PositiveIntegerField(default=10)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('college', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sports_slots', to='colleges.college')),
            ],
            options={
                'db_table': 'sports_court_slots',
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('min_players', models.PositiveIntegerField(default=1)),
                ('max_players', models.PositiveIntegerField(default=10)),
                ('game_type', models.CharField(choices=[('singles', 'Singles'), ('doubles', 'Doubles'), ('team', 'Team'), ('mixed', 'Mixed')], default='team', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('icon', models.CharField(blank=True, default='', max_length=32)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('college', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sports_catalog', to='colleges.college')),
            ],
            options={
                'db_table': 'sports_catalog',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SportsPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_bookings_per_day', models.PositiveIntegerField(default=1)),
                ('max_bookings_per_week', models.PositiveIntegerField(default=3)),
                ('allow_same_sport_same_day', models.BooleanField(default=False)),
                ('booking_window_days', models.PositiveIntegerField(default=7)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('college', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sports_policies', to='colleges.college')),
            ],
            options={
                'db_table': 'sports_policy',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SportSlotBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('attended', 'Attended'), ('no_show', 'No Show')], db_index=True, default='confirmed', max_length=20)),
                ('qr_token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('check_in_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('checked_in_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sports_bookings_checked_in', to=settings.AUTH_USER_MODEL)),
                ('college', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sports_slot_bookings', to='colleges.college')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='sports.courtslot')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sports_slot_bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sports_slot_bookings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SportCourt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('location', models.CharField(blank=True, default='', max_length=180)),
                ('capacity', models.PositiveIntegerField(default=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('maintenance', 'Maintenance'), ('closed', 'Closed')], default='open', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('college', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sports_courts', to='colleges.college')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courts', to='sports.sport')),
            ],
            options={
                'db_table': 'sports_courts',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SportAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_logs', to='sports.sportslotbooking')),
                ('college', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sports_attendance_logs', to='colleges.college')),
                ('scanned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sports_attendance',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DepartmentSportsRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('requested_date', models.DateField()),
                ('requested_start_time', models.TimeField()),
                ('requested_end_time', models.TimeField()),
                ('department', models.CharField(max_length=120)),
                ('year_of_study', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('estimated_players', models.PositiveIntegerField(default=10)),
                ('notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], db_index=True, default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allocated_slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_requests', to='sports.courtslot')),
                ('college', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sports_department_requests', to='colleges.college')),
                ('preferred_court', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_department_requests', to='sports.sportcourt')),
                ('requesting_hod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sports_requests_created', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sports_requests_reviewed', to=settings.AUTH_USER_MODEL)),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_requests', to='sports.sport')),
            ],
            options={
                'db_table': 'sports_department_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='courtslot',
            name='court',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='sports.sportcourt'),
        ),
        migrations.AddIndex(
            model_name='sportslotbooking',
            index=models.Index(fields=['student', 'status'], name='sports_slot_student_abd0cf_idx'),
        ),
        migrations.AddIndex(
            model_name='sportslotbooking',
            index=models.Index(fields=['slot', 'status'], name='sports_slot_slot_id_c615e7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sport',
            unique_together={('college', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='courtslot',
            unique_together={('court', 'date', 'start_time', 'end_time')},
        ),
    ]
