# Generated by Django 4.2.10 on 2026-03-30 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sports', '0005_remove_sportbooking_sb_college_status_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SportFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('location', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Sport Facilities',
            },
        ),
        migrations.AlterModelOptions(
            name='departmentsportsrequest',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sportattendance',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sportspolicy',
            options={},
        ),
        migrations.RemoveField(
            model_name='departmentsportsrequest',
            name='allocated_slot',
        ),
        migrations.RemoveField(
            model_name='departmentsportsrequest',
            name='estimated_players',
        ),
        migrations.RemoveField(
            model_name='departmentsportsrequest',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='departmentsportsrequest',
            name='preferred_court',
        ),
        migrations.RemoveField(
            model_name='departmentsportsrequest',
            name='rejection_reason',
        ),
        migrations.RemoveField(
            model_name='departmentsportsrequest',
            name='requested_end_time',
        ),
        migrations.RemoveField(
            model_name='departmentsportsrequest',
            name='requested_start_time',
        ),
        migrations.RemoveField(
            model_name='departmentsportsrequest',
            name='reviewed_by',
        ),
        migrations.RemoveField(
            model_name='departmentsportsrequest',
            name='year_of_study',
        ),
        migrations.AlterField(
            model_name='departmentsportsrequest',
            name='requesting_hod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dept_sports_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='departmentsportsrequest',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='sportattendance',
            name='scanned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sports_attendances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sportspolicy',
            name='booking_window_days',
            field=models.PositiveIntegerField(default=7),
        ),
        migrations.CreateModel(
            name='SportsMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('title', models.CharField(max_length=150)),
                ('match_date', models.DateTimeField()),
                ('team_a_name', models.CharField(max_length=100)),
                ('team_b_name', models.CharField(max_length=100)),
                ('score_a', models.IntegerField(default=0)),
                ('score_b', models.IntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('summary', models.TextField(blank=True)),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sports.sportfacility')),
                ('legacy_court', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sports.sportcourt')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exclusive_matches_organized', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Sports Matches',
            },
        ),
        migrations.CreateModel(
            name='SportsBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('attended', 'Attended'), ('no_show', 'No Show')], db_index=True, default='confirmed', max_length=20)),
                ('qr_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('check_in_time', models.DateTimeField(blank=True, null=True)),
                ('checked_in_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sport_checkins', to=settings.AUTH_USER_MODEL)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='sports.courtslot')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sport_bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sports_booking',
                'ordering': ['-created_at'],
                'unique_together': {('slot', 'student')},
            },
        ),
        migrations.AlterField(
            model_name='sportattendance',
            name='booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_record', to='sports.sportsbooking'),
        ),
        migrations.DeleteModel(
            name='SportBooking',
        ),
    ]
