# Generated by Django 4.2.10 on 2026-04-06 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('colleges', '0011_remove_college_deleted_at_and_more'),
        ('sports', '0005_courtslot_sport_sportspolicy_sportslotbooking_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SportEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(blank=True, default='', max_length=80)),
                ('total_quantity', models.PositiveIntegerField(default=1)),
                ('issued_quantity', models.PositiveIntegerField(default=0)),
                ('low_stock_threshold', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('available', 'Available'), ('maintenance', 'Maintenance'), ('retired', 'Retired')], default='available', max_length=20)),
                ('storage_location', models.CharField(blank=True, default='', max_length=180)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('college', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sports_equipment', to='colleges.college')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='sports.sport')),
            ],
            options={
                'db_table': 'sports_equipment',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='sportslotbooking',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('waitlisted', 'Waitlisted'), ('cancelled', 'Cancelled'), ('attended', 'Attended'), ('no_show', 'No Show')], db_index=True, default='confirmed', max_length=20),
        ),
        migrations.CreateModel(
            name='SportEquipmentIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('issued', 'Issued'), ('returned', 'Returned')], db_index=True, default='issued', max_length=20)),
                ('due_back_at', models.DateTimeField(blank=True, null=True)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('college', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sports_equipment_issues', to='colleges.college')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='sports.sportequipment')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sports_equipment_issued_by_me', to=settings.AUTH_USER_MODEL)),
                ('issued_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sports_equipment_issues', to=settings.AUTH_USER_MODEL)),
                ('returned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sports_equipment_returned_by_me', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sports_equipment_issues',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['equipment', 'status'], name='sports_equi_equipme_76251d_idx'), models.Index(fields=['issued_to', 'status'], name='sports_equi_issued__54592e_idx')],
            },
        ),
    ]
