# Generated by Django 4.2.10 on 2026-03-30 15:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sports', '0006_sportfacility_alter_departmentsportsrequest_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SportsBooking',
            new_name='SportBooking',
        ),
    ]
