# Generated by Django 4.2.10 on 2026-03-31 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('module', models.CharField(help_text='Module triggering the rule (e.g., Gatepass, Complaint)', max_length=50)),
                ('condition', models.CharField(help_text='Evaluated condition: late_count > 5', max_length=255)),
                ('action', models.CharField(help_text='Action to execute: notify_admin, escalate', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'analytics_automation_rule',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('date', models.DateField(unique=True)),
                ('total_students', models.IntegerField(default=0)),
                ('hostel_occupancy', models.IntegerField(default=0)),
                ('gatepass_count', models.IntegerField(default=0)),
                ('late_count', models.IntegerField(default=0)),
                ('complaints_count', models.IntegerField(default=0)),
                ('overdue_complaints', models.IntegerField(default=0)),
                ('expected_meals', models.IntegerField(default=0)),
                ('actual_meals', models.IntegerField(default=0)),
                ('wastage_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
            ],
            options={
                'db_table': 'analytics_daily_stats',
                'ordering': ['-date'],
            },
        ),
    ]
