# Generated by Django 4.2.10 on 2026-04-01 02:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_automationrule_is_deleted_automationrule_tenant_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trace_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Global Trace ID for request correlation.')),
                ('tenant_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('category', models.CharField(db_index=True, max_length=50)),
                ('total_open', models.PositiveIntegerField(default=0)),
                ('avg_age_hrs', models.FloatField(default=0.0)),
                ('breach_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Complaint Summaries',
            },
        ),
        migrations.CreateModel(
            name='DailyHostelMetrics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trace_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Global Trace ID for request correlation.')),
                ('tenant_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('date', models.DateField(db_index=True)),
                ('total_students', models.PositiveIntegerField(default=0)),
                ('students_present', models.PositiveIntegerField(default=0)),
                ('students_outside', models.PositiveIntegerField(default=0)),
                ('students_on_leave', models.PositiveIntegerField(default=0)),
                ('gate_passes_issued', models.PositiveIntegerField(default=0)),
                ('late_returns_detected', models.PositiveIntegerField(default=0)),
                ('complaint_counts_by_category', models.JSONField(default=dict, help_text='Category-wise count of current open complaints.')),
                ('avg_resolution_time_hrs', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name_plural': 'Daily Hostel Metrics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='DashboardSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trace_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Global Trace ID for request correlation.')),
                ('tenant_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('viewer_role', models.CharField(db_index=True, max_length=50)),
                ('summary_data', models.JSONField(help_text='Serialized dashboard state.')),
                ('expires_at', models.DateTimeField(db_index=True)),
            ],
            options={
                'verbose_name_plural': 'Dashboard Summaries',
            },
        ),
        migrations.CreateModel(
            name='GatePassListView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trace_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Global Trace ID for request correlation.')),
                ('tenant_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('gatepass_id', models.UUIDField(db_index=True)),
                ('student_name', models.CharField(max_length=200)),
                ('registration_num', models.CharField(db_index=True, max_length=50)),
                ('room_info', models.CharField(max_length=100)),
                ('status', models.CharField(db_index=True, max_length=20)),
                ('exit_date', models.DateTimeField(db_index=True)),
            ],
            options={
                'verbose_name_plural': 'GatePass List View (Read Pool)',
            },
        ),
        migrations.DeleteModel(
            name='AutomationRule',
        ),
        migrations.DeleteModel(
            name='DailyStats',
        ),
        migrations.AddIndex(
            model_name='gatepasslistview',
            index=models.Index(fields=['tenant_id', 'status', '-exit_date'], name='analytics_g_tenant__467fd4_idx'),
        ),
        migrations.AddIndex(
            model_name='gatepasslistview',
            index=models.Index(fields=['registration_num', 'status'], name='analytics_g_registr_a7a9e3_idx'),
        ),
        migrations.AddIndex(
            model_name='dashboardsummary',
            index=models.Index(fields=['tenant_id', 'viewer_role', 'expires_at'], name='analytics_d_tenant__a77638_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyhostelmetrics',
            unique_together={('date', 'tenant_id')},
        ),
        migrations.AlterUniqueTogether(
            name='complaintsummary',
            unique_together={('tenant_id', 'category')},
        ),
    ]
