# Generated by Django 4.2.10 on 2026-04-04 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_complaintsummary_dailyhostelmetrics_dashboardsummary_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaintsummary',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='dailyhostelmetrics',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='dashboardsummary',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='gatepasslistview',
            name='deleted_at',
        ),
    ]
