# Generated by Django 4.2.10 on 2026-01-27 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GatePass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('pass_type', models.CharField(choices=[('day', 'Day Pass'), ('overnight', 'Overnight'), ('weekend', 'Weekend'), ('emergency', 'Emergency')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('used', 'Used'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('exit_date', models.DateTimeField()),
                ('entry_date', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField()),
                ('destination', models.CharField(max_length=200)),
                ('approval_remarks', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'gate_passes_gatepass',
                'ordering': ['-exit_date'],
            },
        ),
        migrations.CreateModel(
            name='GateScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('direction', models.CharField(choices=[('in', 'Entry'), ('out', 'Exit')], max_length=10)),
                ('scan_time', models.DateTimeField(auto_now_add=True)),
                ('qr_code', models.CharField(max_length=500, unique=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('gate_pass', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='gate_passes.gatepass')),
            ],
            options={
                'db_table': 'gate_passes_gatescan',
                'ordering': ['-scan_time'],
            },
        ),
    ]
