# Generated by Django 4.2.10 on 2026-02-03 13:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gate_passes", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="gatepass",
            name="qr_code",
            field=models.CharField(blank=True, max_length=500, null=True, unique=True),
        ),
    ]
