# Generated by Django 4.2.10 on 2026-02-07 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gate_passes', '0003_gatepass_qr_code'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='gatepass',
            index=models.Index(fields=['status', 'created_at'], name='gate_passes_status_aa7390_idx'),
        ),
    ]
