# Generated by Django 4.2.27 on 2026-02-07 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gate_passes', '0004_gatepass_gate_passes_status_aa7390_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gatescan',
            name='qr_code',
            field=models.CharField(max_length=500),
        ),
    ]
