# Generated by Django 4.2.27 on 2026-02-09 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gate_passes', '0005_alter_gatescan_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatepass',
            name='actual_entry_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gatepass',
            name='actual_exit_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gatepass',
            name='entry_date',
            field=models.DateTimeField(blank=True, help_text='Scheduled/Planned return time', null=True),
        ),
        migrations.AlterField(
            model_name='gatepass',
            name='exit_date',
            field=models.DateTimeField(help_text='Scheduled/Planned exit time'),
        ),
    ]
