# Generated by Django 4.2.27 on 2026-02-11 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gate_passes', '0006_gatepass_actual_entry_at_gatepass_actual_exit_at_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='gatepass',
            index=models.Index(fields=['-created_at'], name='gate_passes_created_0433af_idx'),
        ),
        migrations.AddIndex(
            model_name='gatescan',
            index=models.Index(fields=['-scan_time'], name='gate_passes_scan_ti_7be416_idx'),
        ),
    ]
