# Generated by Django 4.2.10 on 2026-02-14 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gate_passes', '0007_gatepass_gate_passes_created_0433af_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatepass',
            name='parent_informed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gatepass',
            name='parent_informed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
