# Generated by Django 4.2.10 on 2026-02-16 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gate_passes', '0008_gatepass_parent_informed_gatepass_parent_informed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatepass',
            name='audio_brief',
            field=models.FileField(blank=True, help_text='Audio recording for reason (max 40s)', null=True, upload_to='gate_passes/audio/'),
        ),
    ]
