# Generated by Django 4.2.10 on 2026-02-27 16:23

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gate_passes', '0009_gatepass_audio_brief'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gatepass',
            name='audio_brief',
            field=models.FileField(blank=True, help_text='Audio recording for reason (max 40s)', null=True, storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='gate_passes/audio/'),
        ),
    ]
