# Generated by Django 4.2.10 on 2026-02-28 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gate_passes', '0010_alter_gatepass_audio_brief'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='gatepass',
            index=models.Index(fields=['status', 'exit_date', 'entry_date'], name='gate_passes_status_8044e9_idx'),
        ),
    ]
