# Generated by Django 4.2.10 on 2026-03-01 01:43 (perf_indexes_phase1 - fixed for SQLite compat)

import django.db.models.functions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gate_passes', '0011_gatepass_gate_passes_status_8044e9_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='gatepass',
            name='gate_passes_status_aa7390_idx',
        ),
        migrations.RenameIndex(
            model_name='gatepass',
            new_name='gp_student_exit_idx',
            old_name='gate_passes_student_f1ce75_idx',
        ),
        migrations.RenameIndex(
            model_name='gatepass',
            new_name='gp_created_at_idx',
            old_name='gate_passes_created_0433af_idx',
        ),
        migrations.RenameIndex(
            model_name='gatepass',
            new_name='gp_forecast_idx',
            old_name='gate_passes_status_8044e9_idx',
        ),
        migrations.RenameIndex(
            model_name='gatescan',
            new_name='scan_student_time_idx',
            old_name='gate_passes_student_3ddda6_idx',
        ),
        migrations.RenameIndex(
            model_name='gatescan',
            new_name='scan_global_time_idx',
            old_name='gate_passes_scan_ti_7be416_idx',
        ),
        migrations.AddIndex(
            model_name='gatepass',
            index=models.Index(fields=['status', 'exit_date'], name='gp_status_exit_idx'),
        ),
        migrations.AddIndex(
            model_name='gatepass',
            index=models.Index(fields=['student', 'status'], name='gp_student_status_idx'),
        ),
        migrations.AddIndex(
            model_name='gatescan',
            index=models.Index(fields=['gate_pass', '-scan_time'], name='scan_gatepass_idx'),
        ),
        # Partial indexes moved to AddIndex (not AddConstraint) for SQLite compatibility
        migrations.AddIndex(
            model_name='gatepass',
            index=models.Index(
                condition=models.Q(status='pending'),
                fields=['student', 'created_at'],
                name='gp_pending_student_idx',
            ),
        ),
        migrations.AddIndex(
            model_name='gatepass',
            index=models.Index(
                condition=models.Q(status='approved'),
                fields=['student', 'exit_date'],
                name='gp_approved_student_idx',
            ),
        ),
    ]
