# Generated by Django 4.2.10 on 2026-03-04 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gate_passes', '0013_perf_indexes_fix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gatepass',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='gatepass',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='gatepass',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('used', 'Used'), ('expired', 'Expired')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='gatescan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='gatescan',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True),
        ),
    ]
