# Generated by Django 4.2.10 on 2026-03-12 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gate_passes', '0014_alter_gatepass_created_at_alter_gatepass_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gatepass',
            name='pass_type',
            field=models.CharField(choices=[('day', 'Day Pass'), ('overnight', 'Overnight'), ('weekend', 'Weekend'), ('emergency', 'Emergency'), ('leave', 'Leave')], max_length=20),
        ),
    ]
