# Generated by Django 4.2.10 on 2026-03-12 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gate_passes', '0015_alter_gatepass_pass_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatepass',
            name='entry_security',
            field=models.ForeignKey(blank=True, help_text='Security staff who marked entry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gatepass',
            name='entry_time',
            field=models.DateTimeField(blank=True, help_text='Actual time when student returned', null=True),
        ),
        migrations.AddField(
            model_name='gatepass',
            name='exit_security',
            field=models.ForeignKey(blank=True, help_text='Security staff who marked exit', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_exits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gatepass',
            name='exit_time',
            field=models.DateTimeField(blank=True, help_text='Actual time when student left', null=True),
        ),
        migrations.AlterField(
            model_name='gatepass',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('outside', 'Currently Outside'), ('returned', 'Returned'), ('late_return', 'Late Return'), ('used', 'Used'), ('expired', 'Expired')], db_index=True, default='pending', max_length=20),
        ),
    ]
