# Generated by Django 4.2.10 on 2026-03-13

from django.db import migrations, models


def backfill_movement_status(apps, schema_editor):
    GatePass = apps.get_model('gate_passes', 'GatePass')

    GatePass.objects.filter(status__in=['outside', 'used']).update(movement_status='outside')
    GatePass.objects.filter(status__in=['returned', 'late_return', 'expired']).update(movement_status='returned')
    GatePass.objects.filter(status='approved').update(movement_status='inside')


def reverse_backfill_movement_status(apps, schema_editor):
    GatePass = apps.get_model('gate_passes', 'GatePass')
    GatePass.objects.filter(movement_status='inside').update(movement_status='pending')
    GatePass.objects.filter(movement_status='outside').update(movement_status='pending')
    GatePass.objects.filter(movement_status='returned').update(movement_status='pending')


class Migration(migrations.Migration):

    dependencies = [
        ('gate_passes', '0016_gatepass_entry_security_gatepass_entry_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatepass',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gatepass',
            name='movement_status',
            field=models.CharField(
                choices=[
                    ('pending', 'Pending'),
                    ('inside', 'Inside'),
                    ('outside', 'Outside'),
                    ('returned', 'Returned'),
                ],
                db_index=True,
                default='pending',
                max_length=20,
            ),
        ),
        migrations.RunPython(backfill_movement_status, reverse_backfill_movement_status),
    ]
