# Generated by Django 4.2.10 on 2026-03-20 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gate_passes', '0021_normalize_gatepass_qr_tokens'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='gatepass',
            name='gp_college_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='gatepass',
            name='gp_college_created_idx',
        ),
    ]
