# Generated by Django 4.2.10 on 2026-03-31 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("colleges", "0008_collegepolicy"),
        ("gate_passes", "0022_remove_gatepass_gp_college_status_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gatepass",
            name="college",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_records",
                to="colleges.college",
            ),
        ),
        migrations.AlterField(
            model_name="gatescan",
            name="college",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_records",
                to="colleges.college",
            ),
        ),
    ]
