# Generated by Django 4.2.10 on 2026-03-31 11:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gate_passes", "0023_alter_gatepass_college_alter_gatescan_college"),
    ]

    operations = [
        migrations.AddField(
            model_name="gatepass",
            name="late_count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Total late occurrences for student at time of this pass",
            ),
        ),
        migrations.AddField(
            model_name="gatepass",
            name="late_minutes",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="gatepass",
            name="student_type",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="gatepass",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft (Saved)"),
                    ("pending", "Pending Approval"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("out", "Currently Outside"),
                    ("in", "Returned"),
                    ("completed", "Completed"),
                    ("expired", "Expired"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
    ]
