# Generated by Django 4.2.10 on 2026-04-01 02:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gate_passes', '0025_gatepass_is_deleted_gatepass_tenant_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatepass',
            name='trace_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Global Trace ID for request correlation.'),
        ),
        migrations.AddField(
            model_name='gatescan',
            name='trace_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Global Trace ID for request correlation.'),
        ),
        migrations.AddIndex(
            model_name='gatepass',
            index=models.Index(fields=['tenant_id', 'status'], name='gp_tenant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='gatepass',
            index=models.Index(fields=['tenant_id', '-created_at'], name='gp_tenant_created_idx'),
        ),
    ]
