# Generated by Django 4.2.10 on 2026-04-03 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gate_passes', '0026_gatepass_trace_id_gatescan_trace_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gatepass',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='gatescan',
            name='deleted_at',
        ),
        migrations.AddField(
            model_name='gatepass',
            name='reject_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection by Warden or Security', null=True),
        ),
    ]
