# Generated by Django 4.2.10 on 2026-04-05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0008_remove_leaveapplication_deleted_at_and_more'),
        ('gate_passes', '0027_remove_gatepass_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatepass',
            name='leave_application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gate_passes', to='leaves.leaveapplication'),
        ),
        migrations.AddField(
            model_name='gatepass',
            name='pending_reminded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
