# Generated by Django 4.2.10 on 2026-04-14 12:24

import core.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0012_college_attendance_end_time_and_more'),
        ('gate_passes', '0028_gatepass_pending_reminded_at_and_leave_application'),
    ]

    operations = [
        migrations.CreateModel(
            name='GateLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trace_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Global Trace ID for request correlation.')),
                ('tenant_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, max_length=64)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('college', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='colleges.college')),
            ],
            options={
                'db_table': 'gate_passes_gatelocation',
                'ordering': ['display_order', 'name'],
                'indexes': [models.Index(fields=['college', 'is_active'], name='gate_loc_col_active_idx'), models.Index(fields=['college', 'display_order'], name='gate_loc_col_order_idx')],
            },
            bases=(models.Model, core.models.AuditableModelMixin),
        ),
        migrations.AddConstraint(
            model_name='gatelocation',
            constraint=models.UniqueConstraint(fields=('college', 'name'), name='gate_loc_college_name_uniq'),
        ),
        migrations.AddConstraint(
            model_name='gatelocation',
            constraint=models.UniqueConstraint(fields=('college', 'code'), name='gate_loc_college_code_uniq'),
        ),
    ]
