# Generated by Django 4.2.10 on 2026-04-04 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolepermission',
            name='is_scoped',
            field=models.BooleanField(default=False, help_text='If True, access is restricted to specific hierarchy nodes (e.g. Building B1 only)'),
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='scope_type',
            field=models.CharField(choices=[('college', 'Entire College'), ('building', 'Specific Buildings'), ('floor', 'Specific Floors'), ('personal', 'Own Records Only')], default='college', help_text="Defines the granularity of the role's authority within this module.", max_length=20),
        ),
    ]
