# Generated by Django 4.2.10 on 2026-03-30 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IdempotencyKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, help_text="Scoped key: '<user_id>:<client_key>'", max_length=255, unique=True)),
                ('response_data', models.JSONField(blank=True, help_text='Cached API response for replay.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('expires_at', models.DateTimeField(db_index=True, help_text='Key is automatically purged after this time.')),
            ],
            options={
                'verbose_name': 'Idempotency Key',
                'verbose_name_plural': 'Idempotency Keys',
                'indexes': [models.Index(fields=['key'], name='core_idempo_key_145b58_idx'), models.Index(fields=['expires_at'], name='core_idempo_expires_6bf43d_idx')],
            },
        ),
    ]
