# Generated by Django 4.2.10 on 2026-04-04 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_systemevent_payload_checksum_systemincident_trace_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemincident',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='userfeedback',
            name='deleted_at',
        ),
    ]
