# Generated by Django 4.2.10 on 2026-04-12 16:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0011_remove_college_deleted_at_and_more'),
        ('core', '0005_remove_systemincident_deleted_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemEventDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('websocket', 'WebSocket'), ('push', 'Push'), ('email', 'Email'), ('other', 'Other')], db_index=True, max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('tenant_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Event Delivery',
                'verbose_name_plural': 'System Event Deliveries',
            },
        ),
        migrations.CreateModel(
            name='SystemEventLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(db_index=True, max_length=64)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'System Event Log',
                'verbose_name_plural': 'System Event Logs',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='systemevent',
            index=models.Index(fields=['status', 'priority', '-created_at'], name='core_sysevent_st_pri_crtd_idx'),
        ),
        migrations.AddField(
            model_name='systemeventlog',
            name='system_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='immutable_logs', to='core.systemevent'),
        ),
        migrations.AddField(
            model_name='systemeventdelivery',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_event_deliveries', to='colleges.college'),
        ),
        migrations.AddField(
            model_name='systemeventdelivery',
            name='system_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_deliveries', to='core.systemevent'),
        ),
        migrations.AddIndex(
            model_name='systemeventlog',
            index=models.Index(fields=['system_event', 'created_at'], name='core_sysev_log_ev_crtd_idx'),
        ),
        migrations.AddIndex(
            model_name='systemeventdelivery',
            index=models.Index(fields=['system_event', 'channel'], name='core_sysev_del_ev_ch_idx'),
        ),
    ]
