# Generated by Django 4.2.10 on 2026-04-12 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_systemevent_delivery_log_and_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='idempotencykey',
            name='request_body_sha256',
            field=models.CharField(blank=True, db_index=True, help_text='SHA-256 hex of request body when key was completed; replay requires match.', max_length=64, null=True),
        ),
    ]
