# Generated by Django 4.2.10 on 2026-02-03 13:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tenant",
            old_name="guardian_name",
            new_name="parent_name",
        ),
        migrations.RemoveField(
            model_name="tenant",
            name="guardian_phone",
        ),
        migrations.AddField(
            model_name="tenant",
            name="college_code",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="tenant",
            name="parent_phone",
            field=models.CharField(default="—", max_length=15),
        ),
        migrations.AddField(
            model_name="tenant",
            name="parent_phone_2",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
