# Generated by Django 4.2.10 on 2026-02-03 13:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_rename_guardian_name_tenant_parent_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenant",
            name="parent_phone",
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
