# Generated by Django 4.2.10 on 2026-02-07 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_tenant_parent_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='parent_name',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='parent_phone',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='parent_phone_2',
        ),
        migrations.AddField(
            model_name='tenant',
            name='father_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='tenant',
            name='father_phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='tenant',
            name='guardian_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='tenant',
            name='guardian_phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='tenant',
            name='mother_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='tenant',
            name='mother_phone',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
