# Generated by Django 4.2.27 on 2026-02-09 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_tenant_parent_name_remove_tenant_parent_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='disciplinary_notes',
            field=models.TextField(blank=True, help_text='Internal notes by Warden'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='risk_score',
            field=models.IntegerField(default=0, help_text='Auto-calculated risk score based on disciplinary actions'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='risk_status',
            field=models.CharField(choices=[('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk'), ('critical', 'Critical Risk')], default='low', max_length=20),
        ),
    ]
