# Generated by Django 4.2.10 on 2026-03-03 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_tenant_disciplinary_notes_tenant_risk_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='parent_informed',
            field=models.BooleanField(default=False),
        ),
    ]
