# Generated by Django 4.2.10 on 2026-03-08 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_tenant_created_at_alter_tenant_deleted_at'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['college_code'], name='users_tenan_college_06870a_idx'),
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['risk_status'], name='users_tenan_risk_st_563476_idx'),
        ),
    ]
