# Generated by Django 4.2.10 on 2026-03-31 11:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_student_type_workflow"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="studenttypeauditlog",
            new_name="student_typ_student_8d00ed_idx",
            old_name="st_audit_student_idx",
        ),
        migrations.RenameIndex(
            model_name="studenttypeauditlog",
            new_name="student_typ_new_typ_61e1ba_idx",
            old_name="st_audit_newtype_idx",
        ),
        migrations.RenameIndex(
            model_name="studenttypechangerequest",
            new_name="student_typ_student_0ee394_idx",
            old_name="st_req_student_status_idx",
        ),
        migrations.RenameIndex(
            model_name="studenttypechangerequest",
            new_name="student_typ_status_2f6dac_idx",
            old_name="st_req_status_date_idx",
        ),
        migrations.AlterField(
            model_name="studenttypeauditlog",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="studenttypeauditlog",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, db_index=True, default=None, null=True
            ),
        ),
        migrations.AlterField(
            model_name="studenttypeauditlog",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="studenttypechangerequest",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="studenttypechangerequest",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, db_index=True, default=None, null=True
            ),
        ),
        migrations.AlterField(
            model_name="studenttypechangerequest",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
