# Generated by Django 4.2.10 on 2026-03-31 12:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_rename_st_audit_student_idx_student_typ_student_8d00ed_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='cgpa',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='tenant',
            name='department',
            field=models.CharField(blank=True, help_text='e.g. CS, IT, MECH', max_length=100),
        ),
    ]
