# Generated by Django 4.2.10 on 2026-04-03 01:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0012_studenttypeauditlog_is_deleted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studenttypeauditlog',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='studenttypechangerequest',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='deleted_at',
        ),
        migrations.AddField(
            model_name='studenttypeauditlog',
            name='trace_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Global Trace ID for request correlation.'),
        ),
        migrations.AddField(
            model_name='studenttypechangerequest',
            name='trace_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Global Trace ID for request correlation.'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='trace_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Global Trace ID for request correlation.'),
        ),
        migrations.CreateModel(
            name='HRPermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trace_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Global Trace ID for request correlation.')),
                ('tenant_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('can_view_attendance', models.BooleanField(default=False, help_text='Can view hostel attendance')),
                ('can_raise_complaints', models.BooleanField(default=True, help_text='Can raise complaints')),
                ('can_view_complaints', models.BooleanField(default=False, help_text='Can view complaints for assigned hostel')),
                ('can_assist_reports', models.BooleanField(default=False, help_text='Can view/assist in report generation')),
                ('can_manage_notices', models.BooleanField(default=False, help_text='Can manage notices (create/edit/delete)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hr_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'HR Permission',
                'verbose_name_plural': 'HR Permissions',
            },
        ),
    ]
