# Generated by Django 4.2.10 on 2026-04-13 06:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_studenttypeauditlog_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='plus_two_stream',
            field=models.CharField(blank=True, help_text='e.g. PCM, PCB, Commerce', max_length=50),
        ),
        migrations.AddField(
            model_name='tenant',
            name='tenth_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='tenant',
            name='twelfth_pcm_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='tenant',
            name='twelfth_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
