import type { Role } from '@/types'
import {
  ROLE_ADMIN,
  ROLE_CHEF,
  ROLE_DIRECTOR,
  ROLE_GATE_SECURITY,
  ROLE_HEAD_CHEF,
  ROLE_HEAD_WARDEN,
  ROLE_HOD,
  ROLE_HR,
  ROLE_INCHARGE,
  ROLE_PD,
  ROLE_PRINCIPAL,
  ROLE_PT,
  ROLE_SECURITY_HEAD,
  ROLE_STAFF,
  ROLE_STUDENT,
  ROLE_SUPER_ADMIN,
  ROLE_WARDEN,
} from '@/lib/rbac'
import { CAPABILITIES, type Capability } from '@/core/permissions/capabilities'

const {
  gatePass,
  room,
  attendance,
  complaint,
  leave,
  visitor,
  communication,
  report,
} = CAPABILITIES

export const roleCapabilities: Record<Role, readonly Capability[]> = {
  [ROLE_STUDENT]: [
    gatePass.create,
    gatePass.view,
    room.view,
    room.requestChange,
    attendance.view,
    complaint.create,
    complaint.view,
    leave.create,
    leave.view,
    leave.cancel,
    visitor.preregister,
    visitor.view,
    communication.noticeView,
    communication.messageView,
    communication.messageSend,
  ],
  [ROLE_STAFF]: [
    communication.noticeView,
    communication.messageView,
    communication.messageSend,
  ],
  [ROLE_WARDEN]: [
    gatePass.view,
    gatePass.review,
    gatePass.approve,
    gatePass.reject,
    room.view,
    room.allocate,
    room.deallocate,
    room.assign,
    room.map,
    room.manageRequests,
    attendance.view,
    attendance.mark,
    attendance.markBulk,
    attendance.reviewDefaulters,
    complaint.view,
    complaint.review,
    complaint.resolve,
    leave.view,
    leave.review,
    leave.approve,
    leave.reject,
    visitor.view,
    visitor.checkIn,
    visitor.checkOut,
    visitor.review,
    communication.noticeView,
    communication.messageView,
    communication.messageSend,
    communication.messageModerate,
    report.view,
    report.export,
    report.metricsView,
  ],
  [ROLE_HEAD_WARDEN]: [
    gatePass.view,
    gatePass.review,
    gatePass.approve,
    gatePass.reject,
    room.view,
    room.allocate,
    room.deallocate,
    room.assign,
    room.map,
    room.manageRequests,
    attendance.view,
    attendance.mark,
    attendance.markBulk,
    attendance.export,
    attendance.reviewDefaulters,
    complaint.view,
    complaint.review,
    complaint.resolve,
    complaint.escalate,
    complaint.analytics,
    leave.view,
    leave.review,
    leave.approve,
    leave.reject,
    visitor.view,
    visitor.checkIn,
    visitor.checkOut,
    visitor.review,
    communication.noticeView,
    communication.messageView,
    communication.messageSend,
    communication.messageModerate,
    report.view,
    report.export,
    report.metricsView,
    report.auditView,
  ],
  [ROLE_ADMIN]: [
    ...Object.values(gatePass),
    ...Object.values(room),
    ...Object.values(attendance),
    ...Object.values(complaint),
    ...Object.values(leave),
    ...Object.values(visitor),
    ...Object.values(communication),
    ...Object.values(report),
  ],
  [ROLE_SUPER_ADMIN]: [
    ...Object.values(gatePass),
    ...Object.values(room),
    ...Object.values(attendance),
    ...Object.values(complaint),
    ...Object.values(leave),
    ...Object.values(visitor),
    ...Object.values(communication),
    ...Object.values(report),
  ],
  [ROLE_PRINCIPAL]: [
    complaint.view,
    leave.view,
    communication.noticeView,
    communication.noticeManage,
    communication.messageView,
    report.view,
    report.export,
    report.metricsView,
    report.analyticsView,
  ],
  [ROLE_DIRECTOR]: [
    communication.noticeView,
    report.view,
    report.export,
  ],
  [ROLE_HOD]: [
    communication.noticeView,
    report.view,
  ],
  [ROLE_INCHARGE]: [
    gatePass.view,
    room.view,
    communication.noticeView,
  ],
  [ROLE_CHEF]: [
    attendance.view,
    complaint.view,
    complaint.review,
    communication.noticeView,
  ],
  [ROLE_HEAD_CHEF]: [
    attendance.view,
    complaint.view,
    complaint.review,
    communication.noticeView,
    report.view,
  ],
  [ROLE_GATE_SECURITY]: [
    gatePass.view,
    gatePass.scan,
    gatePass.verify,
    visitor.view,
    visitor.checkIn,
    visitor.checkOut,
  ],
  [ROLE_SECURITY_HEAD]: [
    gatePass.view,
    gatePass.review,
    gatePass.scan,
    gatePass.verify,
    visitor.view,
    visitor.checkIn,
    visitor.checkOut,
    visitor.review,
    report.view,
    report.metricsView,
    report.analyticsView,
  ],
  [ROLE_HR]: [
    room.view,
    attendance.view,
    complaint.view,
    complaint.review,
    leave.view,
    communication.noticeView,
    communication.messageView,
    communication.messageModerate,
    report.view,
    report.export,
  ],
  [ROLE_PD]: [
    communication.noticeView,
    communication.noticeManage,
    report.view,
  ],
  [ROLE_PT]: [
    communication.noticeView,
    report.view,
  ],
} as const

export const getRoleCapabilities = (role?: string | null): Capability[] => {
  if (!role) return []
  return [...(roleCapabilities[role as Role] || [])]
}
