# Generated by Django 4.2.10 on 2026-03-12 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('hall_id', models.CharField(max_length=50, unique=True)),
                ('hall_name', models.CharField(max_length=150)),
                ('capacity', models.PositiveIntegerField()),
                ('location', models.CharField(max_length=200)),
                ('facilities', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_halls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hall_booking_hall',
                'ordering': ['hall_name'],
            },
        ),
        migrations.CreateModel(
            name='HallBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('booking_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('event_name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('review_note', models.CharField(blank=True, max_length=300)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='hall_booking.hall')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hall_bookings', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hall_bookings_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hall_booking_booking',
                'ordering': ['booking_date', 'start_time'],
                'indexes': [models.Index(fields=['hall', 'booking_date'], name='hall_bookin_hall_id_295889_idx'), models.Index(fields=['booking_date', 'status'], name='hall_bookin_booking_92c1b0_idx'), models.Index(fields=['status', 'booking_date'], name='hall_bookin_status_99c175_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='hall',
            index=models.Index(fields=['hall_id'], name='hall_bookin_hall_id_8fd253_idx'),
        ),
        migrations.AddIndex(
            model_name='hall',
            index=models.Index(fields=['is_active'], name='hall_bookin_is_acti_fb69f0_idx'),
        ),
    ]
