# Generated by GitHub Copilot on 2026-03-14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hall_booking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='status',
            field=models.CharField(
                choices=[('open', 'Open'), ('maintenance', 'Maintenance'), ('closed', 'Closed')],
                default='open',
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name='hall',
            index=models.Index(fields=['status'], name='hall_bookin_status_7e8d9f_idx'),
        ),
        migrations.CreateModel(
            name='HallEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'hall_booking_equipment',
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='hallequipment',
            index=models.Index(fields=['is_active'], name='hall_bookin_is_acti_1f99d6_idx'),
        ),
        migrations.CreateModel(
            name='HallSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('blocked', 'Blocked')], default='open', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='hall_booking.hall')),
            ],
            options={
                'db_table': 'hall_booking_slot',
                'ordering': ['hall_id', 'start_time'],
            },
        ),
        migrations.AddIndex(
            model_name='hallslot',
            index=models.Index(fields=['hall', 'is_active'], name='hall_bookin_hall_id_1f9b39_idx'),
        ),
        migrations.AddIndex(
            model_name='hallslot',
            index=models.Index(fields=['hall', 'start_time'], name='hall_bookin_hall_id_41a55f_idx'),
        ),
        migrations.AddField(
            model_name='hallbooking',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hallbooking',
            name='department',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='hallbooking',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='hallbooking',
            name='expected_participants',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hallbooking',
            name='qr_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='hallbooking',
            name='slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='hall_booking.hallslot'),
        ),
        migrations.AlterField(
            model_name='hallbooking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='hallbooking',
            index=models.Index(fields=['slot', 'booking_date'], name='hall_bookin_slot_id_51ff70_idx'),
        ),
        migrations.CreateModel(
            name='HallEquipmentBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_allocations', to='hall_booking.hallbooking')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='hall_booking.hallequipment')),
            ],
            options={
                'db_table': 'hall_booking_equipment_booking',
                'unique_together': {('booking', 'equipment')},
            },
        ),
        migrations.AddIndex(
            model_name='hallequipmentbooking',
            index=models.Index(fields=['equipment', 'booking'], name='hall_bookin_equipme_a5e18f_idx'),
        ),
        migrations.AddField(
            model_name='hallbooking',
            name='requested_equipment',
            field=models.ManyToManyField(blank=True, related_name='bookings', through='hall_booking.HallEquipmentBooking', to='hall_booking.hallequipment'),
        ),
        migrations.CreateModel(
            name='HallAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('attendee_name', models.CharField(max_length=150)),
                ('attendee_identifier', models.CharField(blank=True, default='', max_length=100)),
                ('scan_method', models.CharField(choices=[('qr', 'QR Code'), ('manual', 'Manual Entry')], default='qr', max_length=10)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='hall_booking.hallbooking')),
                ('scanned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hall_attendance_scans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hall_booking_attendance',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='hallattendance',
            index=models.Index(fields=['booking', 'created_at'], name='hall_bookin_booking_34ded4_idx'),
        ),
        migrations.AddIndex(
            model_name='hallattendance',
            index=models.Index(fields=['attendee_identifier'], name='hall_bookin_attende_e45e19_idx'),
        ),
    ]
