# Generated by Django 4.2.10 on 2026-03-20 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hall_booking', '0004_backfill_hallbooking_college'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='hallbooking',
            name='hb_college_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='hallbooking',
            name='hb_college_date_idx',
        ),
        migrations.RenameIndex(
            model_name='hall',
            new_name='hall_bookin_status_5bd3eb_idx',
            old_name='hall_bookin_status_7e8d9f_idx',
        ),
        migrations.RenameIndex(
            model_name='hallattendance',
            new_name='hall_bookin_booking_8610ec_idx',
            old_name='hall_bookin_booking_34ded4_idx',
        ),
        migrations.RenameIndex(
            model_name='hallattendance',
            new_name='hall_bookin_attende_6dedf7_idx',
            old_name='hall_bookin_attende_e45e19_idx',
        ),
        migrations.RenameIndex(
            model_name='hallbooking',
            new_name='hall_bookin_slot_id_5d2f26_idx',
            old_name='hall_bookin_slot_id_51ff70_idx',
        ),
        migrations.RenameIndex(
            model_name='hallequipment',
            new_name='hall_bookin_is_acti_430b4a_idx',
            old_name='hall_bookin_is_acti_1f99d6_idx',
        ),
        migrations.RenameIndex(
            model_name='hallequipmentbooking',
            new_name='hall_bookin_equipme_5144ad_idx',
            old_name='hall_bookin_equipme_a5e18f_idx',
        ),
        migrations.RenameIndex(
            model_name='hallslot',
            new_name='hall_bookin_hall_id_507dbf_idx',
            old_name='hall_bookin_hall_id_1f9b39_idx',
        ),
        migrations.RenameIndex(
            model_name='hallslot',
            new_name='hall_bookin_hall_id_4ebd0e_idx',
            old_name='hall_bookin_hall_id_41a55f_idx',
        ),
    ]
