# Generated by Django 4.2.10 on 2026-04-04 06:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hall_booking', '0006_hall_is_deleted_hall_tenant_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hall',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='hallattendance',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='hallbooking',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='hallequipment',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='hallequipmentbooking',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='hallslot',
            name='deleted_at',
        ),
        migrations.AddField(
            model_name='hall',
            name='trace_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Global Trace ID for request correlation.'),
        ),
        migrations.AddField(
            model_name='hallattendance',
            name='trace_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Global Trace ID for request correlation.'),
        ),
        migrations.AddField(
            model_name='hallbooking',
            name='trace_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Global Trace ID for request correlation.'),
        ),
        migrations.AddField(
            model_name='hallequipment',
            name='trace_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Global Trace ID for request correlation.'),
        ),
        migrations.AddField(
            model_name='hallequipmentbooking',
            name='trace_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Global Trace ID for request correlation.'),
        ),
        migrations.AddField(
            model_name='hallslot',
            name='trace_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Global Trace ID for request correlation.'),
        ),
    ]
