# Generated by Django 4.2.10 on 2026-04-04 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hall_booking', '0007_remove_hall_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hallbooking',
            name='target_audience',
            field=models.CharField(choices=[('hostellers', 'Hostellers'), ('day_scholars', 'Day Scholars'), ('all_students', 'All Students'), ('all', 'Everyone')], default='all_students', max_length=50),
        ),
        migrations.AddField(
            model_name='hallbooking',
            name='target_batches',
            field=models.TextField(blank=True, default='', help_text='Comma separated list of batch years for specific_year targeting.'),
        ),
        migrations.AddField(
            model_name='hallbooking',
            name='target_departments',
            field=models.TextField(blank=True, default='', help_text='Comma separated list of department names for specific_department targeting.'),
        ),
    ]
