# Generated by Django 4.2.10 on 2026-04-06 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hall_booking', '0008_hallbooking_target_audience_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='hall',
            constraint=models.CheckConstraint(check=models.Q(('capacity__gt', 0)), name='hall_capacity_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='hallbooking',
            constraint=models.CheckConstraint(check=models.Q(('end_time__gt', models.F('start_time'))), name='hall_booking_end_time_gt_start_time'),
        ),
        migrations.AddConstraint(
            model_name='hallbooking',
            constraint=models.CheckConstraint(check=models.Q(('expected_participants__isnull', True), ('expected_participants__gt', 0), _connector='OR'), name='hall_booking_expected_participants_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='hallslot',
            constraint=models.CheckConstraint(check=models.Q(('end_time__gt', models.F('start_time'))), name='hall_slot_end_time_gt_start_time'),
        ),
    ]
